cmd/init.go, pkg/devspace/clients/helm/client.go, pkg/devspace/sync/downstream.go
- When the fileMap has changed during processing, do not delete a file
- Fix a nil pointer panic
- Do not create .devspace folder on certain commands
=> Add additional check before deleting a file:

README.md
Fixed a typo in the license section of the README doc
=> fixed typo in license

README.md
Curl needs "Accept: application/json" in request header, else  call 
curl "https://api.github.com/repos/covexo/devspace/releases/latest" fails with following error message 
{
"message": "Unsupported 'Accept' header: [#<Sinatra::Request::AcceptEntry:0x00007f8e4e2f8878 @entry=\"application/vnd.heroku+json; version=3\", @type=\"application/vnd.heroku+json\", @params={\"version\"=>\"3\"}, @q=1.0>]. Must accept 'application/json'.",
"documentation_url": "https://developer.github.com/v3/media"
}
=> Update README.md, fix installation script for Mac

Gopkg.lock, Gopkg.toml, docs/docs/configuration/config.yaml.md, pkg/devspace/config/v1/devspace.go, pkg/devspace/services/sync.go, pkg/devspace/sync/downstream.go, pkg/devspace/sync/sync_config.go, pkg/devspace/sync/upstream.go
/kind feature
resolves #369
New config option bandwidthLimits to specify the sync bandwidth limits.
Yes "github.com/juju/ratelimit" that implements the rate limiting
=> Implementation of #369

cmd/init.go, docs/docs/configuration/config.yaml.md, examples/minikube/.devspace/config.yaml, examples/minikube/.devspace/overwrite.yaml, examples/minikube/README.md, examples/offline-development/.devspace/config.yaml, examples/offline-development/.devspace/overwrite.yaml, examples/offline-development/README.md, pkg/devspace/config/v1/image.go, pkg/devspace/image/build.go
/kind feature
resolves #370
New config option skipPush
=> Implementation of #370 & docs & examples

cmd/deploy.go, cmd/up.go, main.go, pkg/devspace/config/configutil/get.go
/kind feature
resolves #373
New --config-overwrite flag in devspace deploy and devspace up
=> implement config-overwrite flag (#373)

cmd/deploy.go, cmd/up.go, docs/docs/configuration/config.yaml.md, pkg/devspace/builder/docker/docker.go, pkg/devspace/config/v1/terminal.go, pkg/devspace/configure/registry.go, pkg/devspace/services/terminal.go
resolves #390 & #388
Yes new --terminal flag for devspace up and new devspace.terminal.disabled option
No
=> Implement #390 and fix #388

cmd/add.go, pkg/devspace/configure/port.go, pkg/devspace/configure/sync.go
/kind feature
It adds a service-flag to the commands "add port" and "add sync".
New flags to use
no
A bug is solved. If the program compared two maps representing labelSelectors with equal length but different keys, the program ran into a nil pointer. Until now.
=> Impl service flags to add cmd

cmd/connect/cluster.go, cmd/deploy.go, cmd/dev.go, pkg/devspace/build/create_builder.go, pkg/devspace/builder/docker/docker.go, pkg/devspace/builder/docker/docker_test.go, pkg/devspace/builder/kaniko/kaniko.go, pkg/devspace/builder/kaniko/kaniko_test.go, pkg/devspace/cloud/login.go, pkg/devspace/cloud/registry.go, pkg/devspace/configure/image.go, pkg/devspace/dependency/dependency.go, pkg/devspace/docker/client.go, pkg/devspace/generator/language.go, pkg/devspace/services/sync.go, pkg/devspace/sync/sync.go
This pull request changes the following things:
- Don't ask for domain on `devspace cluster connect`
- Fixes an issue where it was not possible to enter a custom registry with port during `devspace init` (#557)
- Fixes an issue where sync was not closing correctly on windows
- Fixes an issue where wrongly configured docker environment variables lead to an error
- Automatically append the .devspace folder to dockerignore during build
- Fixes an issue where the selected language none during devspace init would result in a wrong Dockerfile
=> Improvements

cmd/open.go, pkg/devspace/cloud/cluster.go, pkg/devspace/config/constants/constants.go, pkg/devspace/configure/image.go, pkg/devspace/deploy/helm/deploy.go, pkg/devspace/deploy/helm/deploy_test.go, pkg/devspace/deploy/kubectl/kubectl.go, pkg/devspace/registry/util.go, pkg/util/survey/survey.go
This pull request introduces the following changes:
- Fix #559 & implement unit test for correct image name replacement
- Verify image name during init with docker instead of regex
- Strip tags from image name during devspace init
- On `devspace connect cluster` a default cluster spaces url is configured
=> Parse image name correctly & fix #559

cmd/add/provider.go, cmd/create/space.go, cmd/deploy.go, cmd/dev.go, cmd/init.go, cmd/open.go, cmd/use/space.go, pkg/devspace/cloud/config/versions/latest/latest.go, pkg/devspace/cloud/configure.go, pkg/devspace/cloud/configure_test.go, pkg/devspace/cloud/key.go, pkg/devspace/cloud/print_token.go, pkg/devspace/cloud/resume.go, pkg/devspace/kubectl/client.go, pkg/util/analytics/analytics.go, pkg/util/analytics/cloudanalytics/start.go, pkg/util/kubeconfig/kubeconfig.go, vendor/modules.txt
Changes:
- Fixes #633 & #632
- Change the default value of the switch-context flag for `devspace deploy` and `devspace dev` to true
=> Improve activity detection for sleep mode 

dist/npm/index.js, dist/npm/package-lock.json, dist/npm/package.json
- tags non-stable releases as beta|alpha|rc|... depending on version suffix when publishing to npmjs.com
- asks to remove global folder when running `npm uninstall -g devspace`
- always downloads latest stable (now newest) when package version binary could not be found
=> improve npm publishing and npm uninstall process

cmd/init.go
When users are using `\r\n` newlines in .dockerignore, `devspace init` will add `\r` to the sync ignore rules. This fixes it.
=> trim space (especially \r) for sync ignoreRules

cmd/add/provider.go, pkg/devspace/config/configutil/parse.go, pkg/devspace/config/versions/latest/schema.go
Changes:
- adds a flag --host to `devspace add provider` that allows the user to specify an arbitrary host for this provider
- add config option vars.password which hides the user input
=> Add flag to specify provider host

cmd/sync.go, pkg/devspace/builder/helper/helper.go, pkg/devspace/kubectl/util.go, pkg/devspace/services/port_forwarding.go, pkg/devspace/services/sync.go, pkg/devspace/services/targetselector/target_selector.go, pkg/util/port/port.go
Changes:
- Add --download-on-initial-sync flag to `devspace sync` that is enabled by default (#732)
- Images will now be rebuilt during `devspace dev` if there is no sync path with the image name (#733)
- If a local port is already taken during port forwarding a warning message is shown (#739)
=> Various changes

pkg/devspace/kubectl/util.go
/kind bug
`devspace enter -l label=value` did not work anymore because TargetSelector.skipWait would be true resulting in wait=0s for GetNewestRunningPod() which ends up skipping the loop entirely. This fix makes sure that even when wait=0s, the loop would at least be executed once.
=> fix: devspace enter -l label=value

README.md
resolves #
Yes, just fixing the front-page README.md to a more universal Powershell syntax.
No
I changed the Windows Powershell install command to use `Invoke-WebRequest` instead of `wget`.  wget is not an alias that Powershell has set by default in newer PSCore versions.  Tested on PSCore 6 and 7.  Older versions of Powershell for Windows, 5.1, do have `wget` …
=> Fixed Windows Powershell Command

examples/custom-builder/devspace.yaml, examples/dependencies/dependency1/devspace.yaml, examples/dependencies/dependency2/devspace.yaml, examples/dependencies/devspace.yaml, examples/hooks/devspace.yaml, examples/kaniko/devspace.yaml, examples/kustomize/devspace.yaml, examples/microservices/devspace.yaml, examples/microservices/node/kube/deployment.yaml, examples/microservices/php/chart/templates/deployment.yaml, examples/minikube/chart/templates/deployment.yaml, examples/minikube/devspace.yaml, examples/php-mysql-example/devspace.yaml, examples/profiles/devspace.yaml, examples/quickstart-kubectl/devspace.yaml, examples/quickstart-kubectl/kube/deployment.yaml, examples/quickstart/devspace.yaml, examples/redeploy-instead-of-hot-reload/devspace.yaml, examples/redeploy-instead-of-hot-reload/kube/deployment.yaml, examples/variables/devspace.yaml, pkg/devspace/deploy/kubectl/kubectl_test.go, pkg/devspace/helm/v3/client.go, pkg/devspace/services/port_forwarding.go
Changes:
- Update example deployments from extensions/v1beta1 to apps/v1
- Change default port forward address from '127.0.0.1' -> 'localhost'
- Hide helm deploy messages
=> Hide helm deploy messages & update examples

cmd/deploy.go, cmd/dev.go
Changes:
- Clears the dependency cache if namespace or context is switched
=> Clear dependencies cache on context change

cmd/flags/flags.go, cmd/sync.go, pkg/devspace/config/loader/get.go, pkg/devspace/config/loader/validate.go
- Allows `--config` as flag for all commands to specify where the devspace.yaml is
=> Allow --config for all commands

cmd/dev.go, cmd/list/commands.go, cmd/print.go, cmd/set/var.go, cmd/sync.go, cmd/ui.go, pkg/devspace/config/loader/get.go, pkg/devspace/config/loader/parse.go, pkg/devspace/config/loader/save.go, pkg/devspace/config/loader/testing/fake.go, pkg/devspace/deploy/deployer/kubectl/kubectl_test.go, pkg/devspace/server/server.go
Changes:
- Fixes an issue where --config would not be recognized by the ui server (#935)
- Fixes an issue where --config was not correctly applied for subfolders in `devspace sync` (#937)
- Fixes a long running unit test in the package pkg/devspace/deploy/deployer/kubectl
=> --config fixes

cmd/build.go
- Fixes an issue where `devspace build` would not push images if the current kubernetes context was `minikube` or `docker-desktop`
=> Push image in devspace build with local kubernetes

cmd/set/encryptionkey.go, cmd/set/set.go, pkg/devspace/cloud/cluster.go
- Adds a new command `devspace set encryptionkey` to set the cluster encryptionkey in pipelines (#991)
- Allows deployment of devspace-cloud into another namespace
=> Add `devspace set encryptionkey`

examples/custom-builder/devspace.yaml, pkg/devspace/build/builder/custom/custom.go, pkg/devspace/build/builder/custom/custom_test.go, pkg/devspace/config/versions/latest/schema.go
- Fixes an issue where the `images.*.build.custom.args` were appended instead of prepended
- New `images.*.build.custom.appendArgs` option to append arguments to the build command
- Fixes an issue where multiple custom builds would not be correctly executed
=> Fix custom build command (#1019)

docs/versioned_docs/version-4.7/configuration/profiles/patches.mdx
It took me a long time to understand what was possible with patches. I found a comment on PR #994 that referenced the yaml-patch library[1] devspace is using, and a link to the JSON Patch RFC, so I'm suggesting adding that information here to help future developers.
[1] https://github.com/krishicks/yaml-patch
**What is this pull request for? Which issues does it resolve?** Documentation update to help developers understand patching when creating profiles.
**Does this pull request has user-facing changes?** (e.g. config changes, new/modified commands, new/modified flags) Just documentation.
**Does this pull request add new dependencies?**   No.
=> Add reference to JSON Patch RFC for Patching Semantics

pkg/devspace/build/build.go, pkg/devspace/deploy/deployer/kubectl/builder.go, pkg/devspace/server/enter.go, pkg/devspace/server/logs.go, pkg/devspace/server/port_forward.go, pkg/devspace/server/server.go
- Fixes an issue where kubectl deployments with older versions of kubectl would only deploy a single yaml 
- devspace now caches kubectl clients to avoid the `constructing many client instances from the same exec auth config` warning
- shows docker image building output if all images are disabled besides one
=> Fix kubectl issue & ui client caching

pkg/devspace/build/builder/kaniko/build_pod.go
- fixes an issue where `images.build.kaniko.cache` had no effect
=> fix cache flag for kaniko

cmd/attach.go, cmd/enter.go, cmd/logs.go, examples/kaniko/devspace.yaml, pkg/devspace/build/builder/kaniko/build_pod.go, pkg/devspace/build/builder/kaniko/kaniko.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/services/client.go, pkg/devspace/services/logs.go, pkg/devspace/services/sync.go, pkg/util/hash/hash.go
- New option `images.*.build.kaniko.image` that makes it possible to specify a custom kaniko build image
- New option `images.*.build.kaniko.additionalMounts` that allows to specify additional custom mounts for the kaniko pods
- New `--image` flag for `devspace enter`, `devspace logs & `devspace attach` that selects a pod by the provided devspace config image name
- Fixed an issue that could lead to devspace uploading a corrupt sync binary into a container which resulted in the error `command terminated exit code 139`
=> Custom kaniko image & mounts

pkg/devspace/build/create_builder.go, pkg/devspace/sync/sync_test.go, pkg/devspace/sync/util_test.go, sync/server/downstream_test.go, sync/server/upstream_test.go
Because kaniko is fallback to docker, it should be 2nd priority if both are defined. Currently it is 1st priority which does not sounds like a fallback. Inverting this is more understandable and also more expected from a user perspective.
This PR also has the huge advantage that we can now configure docker and still be able to configure the fallback as well. So far, a common use case is that users need `snapshotMode: full` because they have `RUN chmod ..` lines in their Dockerfiles. Without this settings, the kaniko fallback is effectively useless because the resulting …
=> build: prefer docker over kaniko if both are set

pkg/devspace/build/builder/restart/restart.go, pkg/devspace/build/create_builder.go
- The restart script now always restarts the container process instead of exiting when sync is active in the container.
- Fixes an issue where the docker config was not correctly copied on kaniko fallback
=> fix config copy issue with kaniko fallback

cmd/init.go, cmd/open.go, go.sum, pkg/devspace/build/builder/docker/docker.go, pkg/devspace/build/builder/helper/util.go, pkg/devspace/build/builder/kaniko/kaniko.go, pkg/devspace/build/builder/restart/restart.go, pkg/devspace/configure/image.go
- uses CMD for restart helper if ENTRYPOINT not found/defined because that works for most images (e.g. all language specific images) and using CMD instead of ENTRYPOINT is recommended by Docker because ENTRYPOINT is supposed to just be a shell according to Docker best practices. if that is the best practice, we should just warn about using CMD without knowing ENTRYPOINT but not fail because we can assume that most images have a simple shell in ENTRYPOINT
- init now sets restartContainer, preferSyncOverRebuild, injectRestartHelper, production profile and …
=> enhancements for init command and restart helper

cmd/flags/flags.go, cmd/flags/flags_test.go, cmd/root.go, pkg/util/flags/flags.go
- If the `.env` file cannot be loaded, devspace will only print a warning instead of a fatal
- The flags `--switch-context`, `--namespace` and `--kube-context` can now be used together. `--kube-context` and `--namespace` take precedence over `--switch-context`
- Fixes an issue where the `.env` file could cause issues in combination with devspace-cloud spaces (#1068)
=> Fix devspace cloud .env issue & warning instead of fatal

cmd/create/space.go, cmd/dev.go, cmd/enter.go, cmd/flags/flags.go, cmd/render.go, cmd/root.go, cmd/use/context.go, cmd/use/namespace.go, cmd/use/provider.go, cmd/use/space.go, pkg/devspace/dependency/dependency.go, pkg/devspace/deploy/deploy.go, pkg/devspace/deploy/deploy_test.go, pkg/devspace/deploy/deployer/kubectl/builder.go, pkg/devspace/deploy/deployer/kubectl/kubectl.go, pkg/devspace/deploy/testing/fake.go, pkg/devspace/docker/auth.go, pkg/util/factory/factory.go, pkg/util/factory/testing/factory.go, pkg/util/flags/flags.go, pkg/util/survey/survey.go
- Improves the environment flag parsing. Environment flags can now also be set for every command (e.g. `devspace create space` -> DEVSPACE_CREATE_SPACE_FLAGS)
- Fixes an issue where devspace was not correctly parsing command arguments (#977)
- Fixes a nil pointer in the docker authentification (#1076)
- Fixes an issue where devspace was parsing `kustomize version` incorrectly for newer versions (#859)
=> Several Improvements

cmd/dev.go, cmd/open.go, cmd/ui.go, examples/dependencies/dependency1/devspace.yaml, examples/hooks/devspace.yaml, examples/kustomize/devspace.yaml, examples/microservices/devspace.yaml, examples/minikube/devspace.yaml, examples/php-mysql-example/devspace.yaml, examples/profiles/devspace.yaml, examples/quickstart-kubectl/devspace.yaml, examples/quickstart-kubectl/kube/deployment.yaml, examples/redeploy-instead-of-hot-reload/devspace.yaml, pkg/devspace/config/loader/get.go, pkg/devspace/config/loader/predefined_vars.go, pkg/devspace/dependency/resolver.go, pkg/devspace/server/server.go, pkg/util/git/helper.go, pkg/util/port/port.go
- Adds a new flag `--port` to `devspace open` where the exact port can be specified (#1166)
- Adds a new flag `--host` to `devspace ui` where the hostname can be specified that devspace should listen on (#1163)
- Adds a new predefined variable DEVSPACE_PROFILE that contains the current selected profile (#1160)
- Fixes an issue where the wrong path was taken for DEVSPACE_GIT_COMMIT, when specified in a dependency (#1165)
- Update examples to v1beta9 & remove dscr.io references
=> Implements #1166, #1165, #1163 and #1160

cmd/deploy.go, cmd/dev.go, cmd/restore/restore.go, cmd/restore/vars.go, cmd/root.go, cmd/save/save.go, cmd/save/vars.go, helper/cmd/sync/downstream.go, helper/server/downstream.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/configure/image.go, pkg/devspace/services/sync.go
- Throttle change detection in downstream sync
- Add an option `dev.sync. throttleChangeDetection` to configure throttling of downstream change detection
- Adds `devspace save vars` and `devspace restore vars` that save or restore devspace config variables from kubernetes secrets
- Adds `--save-vars` and `--restore-vars` as flags to `devspace dev` and `devspace deploy`
- Adds new github docker registry option to `devspace init`
=> improvement(sync): add throttling to downstream change detection

cmd/dev.go, cmd/restart.go, cmd/root.go, cmd/sync.go, e2e/tests/dev/dev.go, e2e/tests/run/run.go, e2e/tests/sync/sync.go, helper/cmd/restart.go, helper/cmd/root.go, helper/cmd/tunnel.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/kubectl/logs.go, pkg/devspace/services/client.go, pkg/devspace/services/sync.go, pkg/devspace/sync/initial.go, pkg/devspace/sync/sync.go, pkg/util/log/prefix_logger.go
- Adds a new config option `dev.sync.initialCompareBy` that allows you to specify that a file should only be synced if file size has changed (#1177)
- Adds a new command `devspace restart` that triggers a restart for a container if `dev.sync.onUpload.restartContainer` was specified (#1161)
- Adds a new flag `--print-sync` to `devspace dev` that prints the sync output to the console (#1111)
=> initialCompareBy, devspace restart & --print-sync

cmd/flags/flags.go, cmd/reset/dependencies.go, pkg/devspace/config/loader/get.go, pkg/devspace/config/loader/parse.go, pkg/devspace/config/loader/patches.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/versions.go, pkg/devspace/dependency/resolver.go, pkg/devspace/dependency/resolver_test.go, pkg/devspace/dependency/util/util.go, pkg/devspace/upgrade/upgrade.go
- Fixes an issue where add patches wouldn't work as expected
- Adds a new environment variable `DEVSPACE_SKIP_VERSION_CHECK` to skip the version check (#1198)
- Adds a new config option `profiles.*.parents` that can define multiple parent profiles: (#1199)
```yaml
version: v1beta9
profiles:
- name: multi-parents
parents:
- profile: deployments
- profile: images
- name: deployments
replace:
deployments:
- name: my-deployment
helm:
componentChart: true
values:
containers:
- name: test
- name: images
replace:
images:
test:
image: mydockeruser/devspace
createPullSecret: true
```
- Adds a new config option `profiles.*.parents.*.source` that can define profiles that lie in a different `devspace.yaml`: (#1200)
```yaml
version: v1beta9
profiles:
- name: dev
parents:
- profile: images
source: …
```
=> multiple profile parents & profile sources

pkg/devspace/build/builder/helper/util.go, pkg/devspace/build/builder/kaniko/build_pod.go, pkg/devspace/build/builder/kaniko/kaniko.go, pkg/devspace/sync/tar.go
- Updates kaniko default version to v1.3.0
- Fixes an issue in kaniko build where the target was not set correctly
- Fixes an issue in kaniko build on windows where the restart helper couldn't be injected
- Fixes an issue in kaniko build on windows where files were not executable
=> fix: several kaniko issues

cmd/deploy.go, cmd/dev.go, cmd/restart.go, cmd/sync.go, helper/cmd/root.go, helper/main.go, pkg/devspace/analyze/analyze.go, pkg/devspace/analyze/pods.go, pkg/devspace/build/build.go, pkg/devspace/build/builder/custom/custom.go, pkg/devspace/build/builder/docker/docker.go, pkg/devspace/build/builder/helper/helper.go, pkg/devspace/build/builder/kaniko/build_pod.go, pkg/devspace/build/builder/kaniko/kaniko.go, pkg/devspace/build/create_builder.go, pkg/devspace/config/loader/predefined_vars.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/services/reverse_port_forwarding.go, pkg/devspace/services/sync.go, pkg/devspace/sync/upstream.go, pkg/devspace/tunnel/client.go, pkg/util/git/helper.go, pkg/util/randutil/rand.go
- Fixes a race condition in sync where the initial sync wouldn't wait for uploading a single file (#1223)
- Fixes an issue where `devspace restart` wouldn't work without running `devspace dev` or `devspace sync` prior
- Fixes an issue where pod restarts could lead to a timeout during `devspace deploy/dev --wait`
- New option `tagsAppendRandom` that automatically adds a random suffix to each tag and avoids the rebuilding problem described in #1188
- New predefined variable `DEVSPACE_GIT_BRANCH` that holds the git branch name
=> fix: fixes an initial sync wait race (#1223)

pkg/devspace/build/builder/helper/util.go
- Improves the error message when the restart helper cannot be injected
=> chore: improve message for restart helper error

.github/workflows/release.yaml, assets/assets.go, hack/build-all.bash, pkg/devspace/build/build.go, pkg/devspace/build/builder/kaniko/build_pod.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/versions.go, pkg/devspace/dependency/dependency.go, pkg/devspace/dependency/resolver.go, pkg/devspace/dependency/resolver_test.go, pkg/devspace/dependency/util/util.go, pkg/devspace/deploy/deploy.go, pkg/devspace/hook/hook.go, pkg/devspace/hook/hook_test.go, pkg/devspace/hook/testing/hook.go, pkg/devspace/pullsecrets/init.go, pkg/devspace/server/download.go, pkg/devspace/services/sync.go, pkg/util/command/command.go
- Adds `dependencies.*.vars` to override variables in dependencies
- Adds `images.*.build.kaniko.nodeSelector`, `images.*.build.kaniko.initImage` and `images.*.build.kaniko.serviceAccount`
- Compiles the sync helper binary and ui archive into the devspace binary
- Fixes an issue in dependencies where loading a config with variables from a relative local path command could result in an error
- Adds `onError` for hooks 
- Adds environment variables to hook execution for more context information within hooks
=> hooks, dependencies & kaniko changes

pkg/devspace/build/builder/docker/docker.go, pkg/devspace/build/builder/helper/helper.go, pkg/devspace/build/builder/helper/util.go, pkg/devspace/build/builder/kaniko/build_pod.go, pkg/devspace/build/builder/kaniko/kaniko.go, pkg/devspace/build/builder/restart/restart.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/services/log_manager.go
- Adds `images.*.restartHelperPath`
- Fixes an issue in rebuild detection
- Adds labels & annotations for kaniko build pod
=> RestartHelperPath, rebuild detection fix & build pod annoations / labels

pkg/util/terminal/tty.go
- Fixed an issue where CTRL+C would terminate devspace terminal on older windows versions
=> fix: fixes a windows terminal issue

cmd/analyze.go, go.mod, pkg/devspace/analyze/pods.go
resolves #
`devspace analyze` add `IgnorePodRestarts` flags:
`Usage:
devspace analyze [flags]
Flags:
--ignore-pod-restarts   If true, analyze will ignore the restart events of running pods`
new flags
no
Sometimes pod startup successfully after a couples of restarts.  `devspace analyze` cmd prints LastFaultyExecutionLog for this situation. The new flag …
=> devspace analyze add IgnorePodRestarts flags

cmd/flags/flags.go, pkg/devspace/config/loader/get.go, pkg/devspace/config/loader/parse.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/versions.go, pkg/devspace/dependency/resolver.go
- Adds a new flag `--profile-parent` to devspace, that allows you to specify other profiles via CLI that should be applied before the actual `--profile`
=> feat: add --profile-parent flag

cmd/dev.go, cmd/enter.go, examples/quickstart/.dockerignore, pkg/devspace/config/loader/predefined_vars.go, pkg/devspace/config/loader/validate.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/deploy.go, pkg/devspace/hook/hook.go, pkg/devspace/kubectl/copy.go, pkg/devspace/kubectl/util/util.go, pkg/devspace/services/client.go, pkg/devspace/services/terminal.go, pkg/devspace/services/terminal_test.go, pkg/devspace/sync/sync.go, pkg/devspace/sync/upstream.go
- New options `upload` and `download` for hooks to upload or download files from a container:
```yaml
hooks:
- upload:
localPath: bin
containerPath: bin
where:
container:
imageName: default
when:
after:
deployments: deployment-1
- download:
localPath: build/artifact.jar
containerPath: build/artifact-test.jar
where:
container:
imageName: java
when:
after:
deployments: deployment-2
```
- New predefined variable `${DEVSPACE_VERSION}`
- New options `hooks.when.before.purgeDeployments`, `hooks.when.after.purgeDeployments` and`hooks.when.onError.purgeDeployments` to execute hooks on `devspace purge`
- New option `dev.interactive.terminal.workDir` to specify a working directory to open the terminal in
- New flag `--workdir` for `devspace enter` and `devspace dev` to specify a working directory …
=> DEVSPACE_VERSION, purge hooks & sync fix

cmd/build.go, cmd/deploy.go, cmd/dev.go, cmd/flags/flags.go, cmd/print.go, cmd/purge.go, cmd/render.go, cmd/restart.go, cmd/restore/vars.go, cmd/save/vars.go, cmd/sync.go, cmd/ui.go, cmd/use/profile.go, pkg/devspace/config/loader/get.go, pkg/devspace/config/loader/predefined_vars.go, pkg/devspace/config/loader/restore.go, pkg/devspace/config/loader/testing/fake.go, pkg/devspace/deploy/deployer/kubectl/builder.go, pkg/devspace/deploy/deployer/kubectl/kubectl.go, pkg/devspace/helm/generic/generic.go, pkg/devspace/helm/v2/client.go, pkg/devspace/helm/v3/client.go, pkg/devspace/kubectl/client.go, pkg/devspace/kubectl/testing/client.go, pkg/devspace/kubectl/util/util.go, pkg/devspace/sync/sync.go
- the flags `--save-vars` and `--restore-vars` are now global
- the sync only excludes `.devspace/logs` automatically instead of the complete `.devspace` folder
- fixes an issue where deployment with an in cluster kube context was not possible
=> Global flags, sync exclude & in cluster kube context fix

cmd/sync.go, pkg/devspace/config/loader/validate.go, pkg/devspace/configure/image.go, pkg/devspace/deploy/deployer/util/replace.go, pkg/devspace/kubectl/util.go, pkg/devspace/pullsecrets/util.go, pkg/devspace/upgrade/upgrade.go
- Improves the way `devspace sync --config ...` asks for a sync path by displaying the image or label selector (#1300)
- Allows to define `dev.sync.imageName` and `dev.sync.labelSelector` simultaneously
- Improves the way devspace searches for imageNames that were not previously deployed and have a tag with '#' (#1301) 
- Fixes an issue where a version without 'v' would result in issues during ui & helper download
=> Selector Improvements

cmd/open.go, pkg/devspace/build/builder/kaniko/kaniko.go
- Fixes an issue where devspace would take a long time to upload the building context to the kaniko pod
- Fixes an issue where `devspace open` would not recognize LoadBalancer services
=> fix: improve kaniko upload performance

pkg/devspace/build/builder/custom/custom.go, pkg/devspace/config/loader/validate.go, pkg/devspace/config/versions/latest/schema.go
- New option `images.*.build.custom.skipImageArg` to prevent devspace from adding an argument to the custom command with the image name and tag
- New option `images.*.build.custom.imageTagOnly` to add only the image tag instead of the full image name with tag as argument to the custom command (`my-image-repo.com/repo/image:my-tag` will just become `my-tag`)
- New option `images.*.build.custom.commands` to change the base command depending on the operating system. For example:
```yaml
images:
default:
image: test
tags:
- my-tag
build:
custom:
command: './scripts/my-bash-build-script.sh'
commands:
- command: './scripts/my-powershell-build-script.ps' 
os: windows
```
=> feat: add commands, skipImageArg and imageTagOnly for custom builds

pkg/devspace/config/generated/config.go
- New environment variable `DEVSPACE_DISABLE_VARS_ENCRYPTION` that will disable automatic config variable encryption if set to `true`
=> feat: add environment variable to disable generated vars encryption

hack/build-all.bash, helper/server/downstream.go, helper/server/ignoreparser/ignoreparser.go, helper/server/upstream.go, pkg/devspace/kubectl/copy.go, pkg/devspace/sync/sync.go, pkg/devspace/sync/tar.go, pkg/devspace/sync/upstream.go, pkg/devspace/sync/util.go, pkg/devspace/watch/watch.go
- Fixes an issue where the devspace helper couldn't be executed on docker desktop v3.2.0 (#1334)
- Fixes an issue where negating exclude patterns were not working correctly for sync download (#1335)
=> fix: upgrade devspacehelper to amd64 architecture & fix negating patterns download

docs/pages/configuration/variables/basics.mdx, docs/pages/configuration/variables/source-none.mdx, docs/pages/fragments/vars-default.mdx, pkg/devspace/config/loader/parse.go, pkg/devspace/config/loader/variable/resolver.go, pkg/devspace/config/loader/variable/types.go
- DevSpace now allows to specify variables within other variables default values, which makes it possible to compose variables of other variables. To use a variable in a default value, the variable that is used needs to be specified prior or needs to be a predefined variable. For example:
```yaml
version: v1beta9
images:
default:
image: ${IMAGE}
vars:
- name: IMAGE_REPOSITORY
default: myrepository
source: none
- name: IMAGE_NAME
default: devspace
source: none
- name: IMAGE
default: ${IMAGE_REPOSITORY}/${IMAGE_NAME}
source: none
- name: NAMESPACE
default: ${DEVSPACE_NAMESPACE}
source: none
```
=> feat: allow variables in vars default

pkg/devspace/config/loader/loader.go, pkg/devspace/config/loader/parser.go, pkg/devspace/config/loader/variable/resolver.go, pkg/util/vars/parse.go
- It is now allowed to use variables in the `command`, `args` or `commands` field of other variables. For example these variable definitions are now valid:
```yaml
vars:
- name: SPECIAL_NAMESPACE
command: "./script.sh"
args: ["${DEVSPACE_NAMESPACE"}]
- name: OTHER_VARIABLE
command: "${SPECIAL_NAMESPACE}"
args: ["other-args-${DEVSPACE_NAMESPACE}"]
```
=> feat: allow variables in variable command, args & commands

cmd/purge.go, cmd/run.go, pkg/devspace/command/command.go, pkg/devspace/config/loader/variable/command_variable.go, pkg/devspace/config/loader/variable/resolver.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/dependency/dependency.go, pkg/devspace/hook/local_command.go, pkg/devspace/kubectl/client.go, pkg/util/shell/shell.go
- Added `vars[*].value`, which is a shortcut for using `vars[*].default` and `vars[*].source: none`
- Deprecated the `--dependencies` flag for `devspace purge`, use instead the new flag `--all` and `-a`
- You can now use `devspace run dependency1.command` instead of `devspace --dependency dependency1 run command`
- You can now define shell commands in vars by leaving out the `args`:
```yaml
vars:
- name: FROM_CMD
command: "echo 123"
```
- Added `commands[*].args` that if defined will not execute the command in a golang shell and rather executes the command directly
=> feat: vars.value, commands.args, vars.command & --all

pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/v1beta9/schema.go, pkg/devspace/helm/v3/client.go
/kind feature
resolves https://github.com/loft-sh/devspace/issues/1419
This adds an option in the helm config to enable output. When set to true this allows to show the output from helm install/upgrade during a deploy.
Since this is technically backward compatible I added it to the current schema but I'm not sure if this actually warrants a new version.
I'm also aware this is missing the documentation part. I wanted to get feedback on the implementation/interface first.
**Does this pull request has user-facing changes?** (e.g. config changes, new/modified commands, …
=> Add option to display helm output during install/upgrade

cmd/dev.go, cmd/list/ports.go, cmd/logs.go, cmd/restart.go, cmd/sync.go, main.go, pkg/devspace/config/loader/validate.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/deployer/util/replace.go, pkg/devspace/hook/hook.go, pkg/devspace/hook/remote_hook.go, pkg/devspace/hook/wait.go, pkg/devspace/kubectl/selector.go, pkg/devspace/services/log_manager.go, pkg/devspace/services/podreplace/podreplace.go, pkg/devspace/services/port_forwarding.go, pkg/devspace/services/reverse_port_forwarding.go, pkg/devspace/services/sync.go, pkg/util/imageselector/imageselector.go
- New field `imageSelector` that allows you to select containers for sync, podReplace, port-forwarding etc. by the container image instead of the config name in `images`. This makes it easier for certain use cases as you can now omit the `images` section sometimes completely:
```yaml
version: v1beta10
vars:
- name: IMAGE
value: registry.com/production:latest
deployments:
- name: my-chart
helm:
chart:
name: my-application
values:
image: ${IMAGE}
dev:
terminal:
imageSelector: ${IMAGE}
replacePods:
- imageSelector: ${IMAGE}
replaceImage: registry.com/dev:latest
patches:
- op: replace
path: spec.containers[0].workingDir
value: /app
- op: replace
path: spec.containers[0].command
value: ["sleep"]
- op: replace
path: spec.containers[0].args
value: ["9999999999"]
ports:
- imageSelector: ${IMAGE} …
```
=> feat: add imageSelector

cmd/purge.go, cmd/reset/pods.go, examples/replace-pod/devspace.yaml, pkg/devspace/services/podreplace/podreplace.go, pkg/util/imageselector/imageselector.go
- `devspace reset pods` will now reset scaled down deployments, statefulsets & replicasets even though no resettable pod could be found
=> feat: scale up sets on devspace reset pods

pkg/devspace/config/loader/loader.go, pkg/devspace/config/loader/validate.go
- Having multiple variable definitions with the same name under `vars` throws now an error (#1466)
=> fix: validate vars

docs/pages/configuration/dependencies/git-repository.mdx, docs/pages/configuration/dependencies/local-folder.mdx, docs/pages/fragments/config-dependencies.mdx, docs/pages/fragments/dependency-overwrite-vars.mdx, docs/versioned_docs/version-5.14/configuration/dependencies/git-repository.mdx, docs/versioned_docs/version-5.14/configuration/dependencies/local-folder.mdx, docs/versioned_docs/version-5.14/fragments/config-dependencies.mdx, docs/versioned_docs/version-5.14/fragments/dependency-overwrite-vars.mdx, docs/versioned_docs/version-5.14/fragments/selector-image-selector.mdx, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/dependency/resolver.go, pkg/devspace/services/podreplace/podreplace.go
- New `dependencies[*].overwriteVars` option to disable variable overwriting in dependencies (#1466)
- DevSpace will now automatically reset the parent deployment, statefulset or replicaset during `devspace dev` if a replaced pod cannot be found, but the parent was scaled down already
=> feat: new dependencies[*].forwardVars option

pkg/devspace/config/versions/latest/schema.go, pkg/devspace/sync/initial.go
- Added `deployments[*].helm.values.service.ports[*].name` to schema (#1472)
- DevSpace doesn't traverse excluded paths locally anymore during initial sync
=> refactor: avoid unnecessary traversing during initial sync

pkg/devspace/helm/generic/generic.go
/kind bug
resolves #1446
no
no
Helm changed the URL for their stable and incubator charts last year. The old URLs were deprecated in November.
https://helm.sh/blog/new-location-stable-incubator-charts/
=> Use new stable repo URL for `stable/` prefix

pkg/devspace/hook/wait.go
- DevSpace will now also wait for selected containers by `hooks[*].wait` to become ready instead of just running (#1489)
=> improvement: check if container ready in hooks[*].wait

pkg/devspace/helm/generic/generic.go, pkg/devspace/helm/v2/client.go, pkg/devspace/helm/v3/client.go
/kind bug
resolves #1493 #1494 
Only for the users who have issues of running devspace on Linux M1 machine.
No
#1493 was caused by the wrong version of helm and devspacehelper.
I think hack/build-all.bash also needs to be fixed for building devspacehelper. I manually built devspacehelper and copy it to $HOME/.devspace, then the sync issue was gone.
=> fix hard-coded architecture

cmd/ui.go
- Fixed an issue where `devspace ui` would panic if no `devspace.yaml` was present (#1510)
=> fix: fixes a nil pointer in devspace ui

helper/server/downstream.go, pkg/devspace/sync/sync.go
- Fixes an issue where the sync watcher would exclude paths if the initial stat of them has failed
=> fix: still watch if stat errors

docs/pages/configuration/development/file-synchronization.mdx, docs/pages/configuration/development/port-forwarding.mdx, docs/pages/configuration/development/reverse-port-forwarding.mdx, docs/pages/configuration/reference.mdx, pkg/devspace/config/loader/loader_test.go, pkg/devspace/config/versions/latest/schema.go
- New option `name` for `dev.sync` and `dev.ports`. This can be used as a steady identifier when using profile patches. (#1577)
=> feat(config): add name to dev.sync & dev.ports

docs/pages/configuration/development/log-streaming.mdx, docs/pages/configuration/hooks/basics.mdx, docs/pages/configuration/reference.mdx, examples/minikube/Dockerfile, pkg/devspace/build/builder/custom/custom.go, pkg/devspace/config/loader/validate.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/hook/hook.go, pkg/devspace/hook/remote_command.go, pkg/devspace/services/log_manager.go, pkg/devspace/services/synccontroller/controller.go, pkg/devspace/sync/downstream.go, pkg/devspace/sync/initial.go, pkg/devspace/sync/sync.go, pkg/devspace/sync/upstream.go, pkg/util/log/prefix_logger.go, ui/package.json, ui/src/lib/fetch.ts
- New `dev.logs.selectors[*].imageSelector` option to select images that should be logged by image name
- Fixed an issue where DevSpace would get stuck uploading or downloading files that would change frequently (#1576)
- Fixed an issue where `http` was hardcoded as target domain in DevSpace UI (#1574)
- Removed red from log streaming color palette to avoid confusion with errors (#1583)
- DevSpace will now run remote hook commands in a remote shell if no args are specified. For example this is now possible:
```yaml
hooks:
- command: |
echo 123
echo 456
echo 789
where:
container:
imageSelector: my-image
when:
after:
deployments: all
```
- New `hooks[*].when.before.initialSync` and `hooks[*].when.after.initialSync` that executes a hook after or before a certain sync configuration's initial …
=> Multiple Improvements

docs/pages/configuration/dependencies/git-repository.mdx, docs/pages/configuration/dependencies/local-folder.mdx
- Document `dependencies.[*].source.configName` option to override DevSpace configuration file name
=> docs: document configName for dependency sources

docs/pages/configuration/development/file-synchronization.mdx, docs/pages/configuration/reference.mdx, e2e/new/framework/helper.go, e2e/new/tests/sync/sync.go, e2e/new/tests/sync/testdata/sync-exclude-file/.gitignore, e2e/new/tests/sync/testdata/sync-exclude-file/.gitignore-download, e2e/new/tests/sync/testdata/sync-exclude-file/.gitignore-upload, e2e/new/tests/sync/testdata/sync-exclude-file/devspace.yaml, e2e/new/tests/sync/testdata/sync-exclude-file/file-exclude.txt, e2e/new/tests/sync/testdata/sync-exclude-file/file-include.txt, e2e/new/tests/sync/testdata/sync-exclude-file/file-upload-exclude.txt, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/services/synccontroller/controller.go
- Add `excludeFile`, `downloadExcludeFile`, and `uploadExclude` options for loading exclude paths from files using `.gitignore` syntax (#1562)
=> feat: use files for excluding paths from synchronization

cmd/root.go, pkg/devspace/plugin/hook.go
- Fixed an issue where devspace would return `Fatal: nil` or fail to encode plugin context information
=> fix: fixes plugin config issue & nil fatal

pkg/devspace/config/versions/latest/schema.go
Resolves #1632 
The ingress parameter "pathType" is mandatory from version 5.15. If the parameter is omitted, the following error appears:
`spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified`
But if try to set it, another error appears:
`field pathType not found in type latest.IngressRuleConfig`
This change adds ability to specify 'pathType' parameter.
=> #1632: Add path type to schema

cmd/attach.go, cmd/enter.go, cmd/logs.go, cmd/set/var.go, pkg/devspace/config/loader/expression/expression.go, pkg/devspace/config/loader/loader.go, pkg/devspace/config/loader/loader_test.go, pkg/devspace/config/loader/parser.go, pkg/devspace/deploy/deployer/helm/client.go, pkg/devspace/deploy/deployer/util/replace.go, pkg/devspace/hook/download.go, pkg/devspace/hook/local_command.go, pkg/devspace/hook/logs.go, pkg/devspace/hook/remote_command.go, pkg/devspace/hook/remote_hook.go, pkg/devspace/hook/upload.go, pkg/devspace/server/command.go, pkg/util/vars/parse.go
- Fixed an issue where `pathType` was not automatically set for newer ingress versions
- Fixed an issue where namespace and context were wrong in UI commands
- New flag `--image-selector` for commands `devspace enter`, `devspace logs` & `devspace attach`
- You can now use `image(default)` and `tag(default)` in hook commands and args:
```yaml
images:
test:
image: test/test
hooks:
- command: |-
./custom-script image(test):tag(test) # -> Transformed to ./custom-script test/test:##### 
when:
after:
images: all
```
- New feature config expressions `${{ any valid bash expression }}` that are evaluated after variables are loaded and can be used to generate certain fields of the devspace yaml dynamically:
Only build if user uses `devspace deploy`
```yaml
images:
default:
build: |-
${{ 
if [ "$1" …
```
=> Component Chart & UI commands namespace and context

docs/versioned_docs/version-5.16/configuration/development/file-synchronization.mdx, docs/versioned_docs/version-5.16/configuration/reference.mdx, pkg/devspace/plugin/installer.go
- Fixed an issue where `devspace add plugin` wouldn't work with absolute file paths
- Added `excludeFile` option to docs
=> Absolute Filepaths Fix & Docs

cmd/dev.go, cmd/enter.go, pkg/devspace/services/terminal.go
- DevSpace will not reconnect the terminal if the exit code 0,1,2,126,127,128 or 130 is encountered (https://shapeshed.com/unix-exit-codes/)
=> refactor: exclude some exit codes from terminal reconnect

examples/quickstart/devspace.yaml, pkg/devspace/services/sync.go, pkg/util/log/union_logger.go
- DevSpace will now also write sync logs to `.devspace/logs/sync.log` even if shown in terminal
=> refactor: union logger & log sync also if shown

e2e/tests/replacepods/replacepods.go, e2e/tests/replacepods/testdata/statefulset/devspace.yaml, e2e/tests/replacepods/testdata/statefulset/statefulset.yaml, pkg/devspace/services/podreplace/podreplace.go
- DevSpace will now set the statefulsets pod name as hostname in the replaced pods
=> refactor: set old pod as hostname & new e2e test

docs/pages/configuration/hooks/basics.mdx, docs/pages/fragments/config-hooks.mdx, e2e/e2e_suite_test.go, e2e/tests/hooks/framework.go, e2e/tests/hooks/hooks.go, e2e/tests/hooks/testdata/once/devspace.yaml, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/hook/download.go, pkg/devspace/hook/logs.go, pkg/devspace/hook/remote_command.go, pkg/devspace/hook/remote_hook.go, pkg/devspace/hook/upload.go
- Add new option: `hooks[*].container.once` that will configure remote container command hooks to run only once per deployment
=> feat: add option to execute hooks once

docs/pages/configuration/development/replace-pods.mdx, docs/pages/configuration/reference.mdx, pkg/devspace/build/builder/buildkit/buildkit.go, pkg/devspace/build/builder/docker/docker.go, pkg/devspace/build/builder/helper/helper.go, pkg/devspace/build/builder/kaniko/build_pod.go, pkg/devspace/build/builder/kaniko/util/util.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/services/podreplace/persist.go
- New option `dev.replacePods.persistPaths.initConainter.resources` to configure resources for the pre-populating init container (#1775)
- DevSpace will now print by default why it is rebuilding an image
=> feat: resources option for pre-populate init container

pkg/devspace/dependency/dependency.go, pkg/devspace/dependency/graph.go, pkg/devspace/dependency/graph_test.go, pkg/devspace/dependency/util/util.go
- Log dependency names instead of IDs
=> fix: log dependency name instead of id

.github/workflows/release.yaml, hack/build-all.bash
- use `CGO_ENABLED=1` for `darwin` builds to prevent `too many files open` issue
=> build: test cgo build for darwin/arm64

pkg/devspace/services/podreplace/persist.go
- DevSpace will now use the `replacePods[*].containerName` if multiple containers are found within a replaced pod and no `replacePods[*].persistPaths[*].containerName` is defined
=> refactor: use replacePods[*].containerName if persitPath.containerName not found

pkg/devspace/services/podreplace/persist.go, pkg/devspace/services/podreplace/replace.go
- Fixed an issue where DevSpace would create a failing pod if the persistence path would not exist in the target container
=> fix: don't fail if folder doesn't exist & logging

pkg/devspace/sync/evaluater.go, pkg/devspace/sync/upstream.go
- DevSpace will now print all filesystem events it receives for syncing files if `--debug` is specified and show if a file wasn't synced
=> Show file system events for sync in debug

docs/pages/configuration/profiles/activation.mdx, e2e/tests/config/config.go, e2e/tests/config/testdata/profile-activation/regexp-exact.yaml, e2e/tests/config/testdata/profile-activation/regexp-substring.yaml, e2e/tests/config/testdata/profile-activation/string-exact.yaml, pkg/devspace/config/versions/versions.go
- Prevents substring matches from activating profiles. For example: an expression `test` should not match `test123`
=> fix: profiles should not activate on substring matches

dist/npm/index.js
- add support for arm64 architecture
- use the given binary directory when finalizing install
=> fix: use the given binary path when finishing the install with npm/yarn

pkg/devspace/kubectl/selector/selector.go
Adds the container name to error messages like `couldn't find pod / container with label selector ...`
=> refactor: add containername to error messages

pkg/devspace/config/loader/patch/operation_test.go, pkg/devspace/config/loader/profile.go, pkg/devspace/config/loader/profile_test.go
- modify patch path conversion to account for possible integer types.
- This does not account for floating point numbers, but that is unlikely to be needed
=> fix: allow matching of integers using older patch path syntax

cmd/run.go, pkg/devspace/config/loader/loader.go, pkg/devspace/config/loader/options.go
/kind bugfix
Fixed an issue where DevSpace would change the generated.yaml in plugin or unrelated commands
=> fix: prevent generated update in `devspace` command building

cmd/init.go, cmd/init_test.go, e2e/framework/util.go, e2e/tests/init/init.go, e2e/tests/init/testdata/new/chart/Chart.yaml, e2e/tests/init/testdata/new/chart/templates/deployment.yaml, e2e/tests/init/testdata/new/chart/templates/service.yaml, e2e/tests/init/testdata/new/chart/values.yaml, e2e/tests/init/testdata/new/kustomization/deployment.yaml, e2e/tests/init/testdata/new/kustomization/kustomization.yaml, e2e/tests/init/testdata/new/manifests/deployment.yaml, pkg/devspace/configure/deployment.go
- `devspace init`: changed `"What is the main container image of this project...?"` question to present images parsed from the given deployment method
- `devspace init`: added tests for component chart, local chart, kubectl and kustomize deployments, and ensured that `devspace dev` can run successfully after accepting defaults
- `devspace init`: validate that the answer given for `"Please enter the paths to your Kubernetes manifests"` matches at least one file
- e2e tests: made temporary directories non-numeric to prevent helm deployment tests from failing
/kind bugfix
Resolves an issue …
=> devspace init + devspace dev fails

cmd/purge.go, pkg/devspace/services/targetselector/until_newest_running.go
- Only show init container logs on `--debug`
=> refactor: only show init container logs if --debug is specified

docs/pages/configuration/images/kaniko.mdx
Signed-off-by: Taras Bondarchuk <alius.miles@gmail.com>
/kind bugfix
**What does this pull request do? Which issues does it resolve?** 
Fix documentation for kaniko custom pull secret: 
provided examples didn't work because devspace was generating kaniko pod with different key in secret mount (*.dockerconfigjson* instead of *config.json*) with pod getting stuck at init with error: `non-existent secret key: .dockerconfigjson`
Fixed documentation for kaniko custom pull secret examples.
I assume this is caused by following line: …
=> fix: kaniko custom-pull-secret documentation

pkg/devspace/config/loader/validate.go, pkg/devspace/config/loader/validate_test.go, pkg/devspace/kubectl/selector/selector.go
/kind bugfix
Fixed an issue where DevSpace wasn't able to use `imageSelector` and `containerName` together
=> fix: allow container name & image selector together

e2e/tests/pullsecret/pullsecrets.go, e2e/tests/pullsecret/testdata/simple/devspace.yaml, pkg/devspace/pullsecrets/registry.go
- Enable multiple pull secrets to used by a single service account
=> feat: enable multiple pull secrets to be used by a service account

e2e/framework/helper.go, e2e/tests/pipelines/pipelines.go, e2e/tests/pipelines/testdata/run_default_pipeline/devspace.yaml, e2e/tests/pipelines/testdata/run_pipelines/devspace.yaml, pkg/devspace/pipeline/engine/pipelinehandler/commands/create_deployments.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/run_default_pipeline.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/run_pipelines.go
Added --set and --set-string flags to run_pipelines and run_default_pipeline commands
/kind test
Added e2e tests for both run_pipelines and run_default_pipeline new flags
resolves #
Two flags are now available for run_pipelines and run_default_pipeline.
NA
NA
=> Added --set and --set-string flags to run_pipelines and run_default_pipeline commands along with e2e tests

pkg/util/strvals/strvals.go, pkg/util/strvals/strvals_test.go
Sets the keys to null when they are added to flags.
resolves #
=> Add unset nature to set and set string flags

docs/pages/configuration/images/kaniko.mdx, pkg/devspace/build/builder/kaniko/build_pod.go
I'm hitting [this pretty nasty bug](https://github.com/GoogleContainerTools/kaniko/issues/1262) with kaniko that seems to be fixed with kaniko 1.8+. I tested with 1.8.1 by overriding the value in devspace.yaml and it solves it.
1.6.0 is a year old so figured it would be a good idea to get devspace aligned with the most recent version.
also updated the documentation, it was misaligned with the current default.
resolves #
Upgrade default kaniko version
Fixed an issue where DevSpace …
=> Bump kaniko default version from v1.6.0 to v1.8.1

cmd/run_pipeline.go, e2e/tests/build/build.go, pkg/devspace/dependency/registry/registry.go, pkg/devspace/kubectl/util/util.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/build_images.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/create_deployments.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/ensure_pull_secrets.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/exec_container.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/purge_deployments.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/select_pod.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/start_dev.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/stop_dev.go, pkg/devspace/pipeline/pipeline.go
/kind bugfix
Earlier for non-existing kubeconfigs, we used to create fakeclientset, I have removed that logic now. If the kubeconfig is needed  for build operation using kaniko and buildkit, there are already checks present to validate. If the docker build is fired, we don't need k8s cluster, so its now executed without any error.
resolves #
=> removed fake k8s client

cmd/run_pipeline.go, pkg/devspace/kubectl/client.go
/kind bugfix
Fixed an issue where DevSpace would not save selection in last kube context
=> fix: fixed context selection issue

.github/workflows/npm.yaml, .github/workflows/release.yaml, dist/npm/bin/devspace, dist/npm/index.js, hack/build-all.bash, hack/build-ui.bash
=> build: fix pipeline fixed version problems

cmd/run.go, e2e/tests/deploy/deploy.go, e2e/tests/replacepods/replacepods.go, helper/server/tar.go, pkg/devspace/config/loader/loader_test.go, pkg/devspace/config/loader/variable/legacy/replace.go, pkg/devspace/config/loader/variable/resolver.go, pkg/devspace/config/loader/variable/runtime/runtime_variable.go, pkg/devspace/config/versions/v1beta11/upgrade.go, pkg/devspace/deploy/deployer/kubectl/kubectl.go, pkg/devspace/imageselector/image_selector.go, pkg/devspace/services/podreplace/builder.go, pkg/devspace/sync/sync_test.go, pkg/devspace/sync/util.go, pkg/util/encoding/encoding.go, pkg/util/flags/flags.go, pkg/util/yamlutil/yaml.go
Replace `strings.Replace(s, old, new, -1)` with `strings.ReplaceAll(s, old, new)`. `strings.ReplaceAll` is a wrapper function for `strings.Replace`, but `strings.ReplaceAll` is more readable and removes the hardcoded `-1`.
N/A, this is a non-user facing change
=> refactor: replace strings.Replace with strings.ReplaceAll

.golangci.yml, helper/util/conn.go, pkg/devspace/deploy/deployer/helm/deploy.go, pkg/devspace/deploy/deployer/helm/deploy_test.go
/kind bugfix
resolves #2097
Fixed an issue where DevSpace wouldn't print an error if reading a helm values file failed
=> fix: show error if yaml reading failed

e2e/tests/build/build.go, helper/server/chown_unsupported.go, pkg/devspace/build/builder/buildkit/buildkit.go, pkg/devspace/build/builder/docker/docker.go, pkg/devspace/kubectl/util.go, pkg/util/idle/idle_darwin.go, pkg/util/idle/idle_windows.go
resolves #
Fixed an issue where DevSpace ...now loads local images to kind cluster in case it is the kind context.
=> added kind support

docs/pages/configuration/commands/README.mdx, docs/pages/configuration/dependencies/git-repository.mdx, docs/pages/configuration/dependencies/local-folder.mdx, docs/pages/configuration/dev/connections/restart-helper.mdx, docs/pages/configuration/pullSecrets/README.mdx, pkg/devspace/services/podreplace/builder.go
resolves #2118
DevSpace will now copy over the labels and annotations to the replaced deployment
=> refactor: copy meta to replaced deployment

e2e/tests/replacepods/replacepods.go, e2e/tests/replacepods/testdata/deployment/devspace.yaml, pkg/devspace/pipeline/engine/pipelinehandler/handler.go, pkg/devspace/services/podreplace/builder.go, pkg/devspace/services/podreplace/replace.go
/kind bugfi
Fixed an issue where DevSpace wouldn't update the replaced deployment correctly
=> feat: allow command override

pkg/devspace/config/versions/latest/schema.go
resolves #
It just fixes a documentation error I found :-)
Fixed schema documentation for SourceConfig struct
=> Update SourceConfig documentation

cmd/completion.go, docs/pages/cli.md, docs/pages/cli/devspace_completion.md
Signed-off-by: Nico Berlee <nico.berlee@on2it.net>
/kind feature
Add fish completion support
Add completion generation support for fish shell
not sure what happend to cli.md, the documenation generation did that... shall I remove it from the commit?
=> feat: add fish completion

pkg/devspace/devpod/devpod.go
/kind bugfix
The following replaces the devImage correctly:
```yaml
dev:
loft:
labelSelector:
app: loft
devImage: loftsh/go
```
However the following format fails to replace the image with the devImage:
```yaml
dev:
loft:
labelSelector:
app: loft
containers:
manager:
devImage: loftsh/go
```
Fixed an issue where DevSpace would not process multiple named dev containers
=> fix: dev containers not being processed in nested format

docs/pages/configuration/imports/README.mdx
I just tried it and devspace will attempt to clone the repository directly from the URL. So received this error:
```
warn Error cloning or pulling git repository github.com/lianmakesthings/devspace-shared/devspace.yaml: Error running 'git clone github.com/lianmakesthings/devspace-shared/devspace.yaml /Users/lianmakesthings/.devspace/dependencies/github-com-lianmakesthings-devspace-shared-devspace-yaml --depth 1': error executing 'git clone github.com/lianmakesthings/devspace-shared/devspace.yaml /Users/lianmakesthings/.devspace/dependencies/github-com-lianmakesthings-devspace-shared-devspace-yaml --depth 1':  -> fatal: repository …
```
=> fixes import URL

docs/pages/configuration/profiles/README.mdx, docs/pages/configuration/profiles/activation.mdx, docs/pages/configuration/profiles/merge.mdx, docs/pages/configuration/profiles/patches.mdx, docs/pages/configuration/profiles/replace.mdx, docs/sidebars.js
=> docs: add profiles documentation

pkg/devspace/pipeline/engine/basichandler/commands/run_watch.go
=> feat: add --exclude to run_watch

pkg/devspace/config/versions/latest/schema.go, pkg/devspace/services/ssh/config.go, pkg/devspace/services/ssh/port.go, pkg/devspace/services/ssh/ssh.go
=> refactor: use ~/.ssh/config as default

e2e/tests/config/config.go, e2e/tests/config/testdata/patch-add-dont-overwrite-existing-key/devspace.yaml, pkg/devspace/config/loader/patch/operation.go
/kind bugfix
/kind test
N/A
Fixed an issue where DevSpace add patch operations on existing keys breaks patching.
This fixes an issue where adding an already existing key to a map would basically append the value in your patch to the key. Unfortunately this would basically shift the yaml around so now the previous value would be the key on the next line. Example: 
```
importme:
build:
buildKit: {}
context: ../..
veryimportantpath: dockerfile
./Dockerfile: image …
```
=> fix: op patching to not add elements if key already exists

pkg/devspace/services/sync/controller.go, pkg/devspace/services/sync/controller_test.go
/kind bugfix
resolves #2221
Fixed an issue where DevSpace would not parse absolute paths on windows correctly
=> fix: sync path parsing for windows

docs/pages/configuration/pipelines/README.mdx, docs/pages/configuration/variables.mdx
=> docs: add pipeline examples

pkg/devspace/helm/v3/client.go
/kind bugfix
Fixes v6.0.0-beta.0 issue where helm registry login for OCI charts did not supply target registry.
Fixed missing `registry` argument for `helm registry login`
I'm not a Go developer, so have mercy.
=> fix: supply helm registry for oci login

pkg/devspace/config/versions/latest/schema.go
resolves #
Updates ChartConfig comments to document OCI support for Helm charts
Document OCI in schema
=> docs: document oci usage for helm ChartConfig

pkg/devspace/dependency/util/util.go, pkg/devspace/deploy/deployer/helm/deploy.go, pkg/devspace/helm/testing/client.go, pkg/devspace/helm/types/interface.go, pkg/devspace/helm/v3/client.go, pkg/util/hash/hash.go
/kind bugfix
When using a helm chart with no name, the current directory is used to detect chart changes. If the current directory contains the `.devspace` folder, it will always detect changes and redeploy the application. This issue presented when using a git repository chart source in a dependency.
Fixed an issue where DevSpace would always re-deploy charts imported using git.
=> fix: use chart directory to detect chart changes

pkg/devspace/config/versions/adjust.go
/kind bugfix
resolves #2245
Fixed an issue where DevSpace would panic if there would be an empty pipeline, var, command, pullSecret or dev config
=> fix: nil pointer if empty config section

pkg/devspace/deploy/deployer/helm/render.go, pkg/devspace/helm/v3/client.go
**What does this pull request do? Which issues does it resolve?** 
Prevent downloading helm charts twice for `devspace render` / `devspace deploy --render`
Prevent downloading helm charts twice for `devspace render` / `devspace deploy --render`
=> fix: download once during render / deploy --render

cmd/run.go, pkg/devspace/config/loader/loader.go, pkg/devspace/config/loader/variable/undefined_variable.go, pkg/util/log/stream_logger.go
=> fix: don't ask question if devspace is not used in terminal

cmd/init.go
/kind bugfix
resolves #2217 
Silent params value being true used to discard the logs, setting it to false will now show the logs on the terminal when --debug is enabled. 
Setting the silent flag to true so that the error in init command will be output on the terminal when --debug is enabled
=> Set silence flag to false in devspace init command to show logs on the screen

pkg/devspace/docker/auth.go, pkg/devspace/pullsecrets/init.go
/kind bugfix
resolves #2278
Fixed an issue where DevSpace skipped creating a pull secret when logged in with Azure container registry.
=> fix: use identity token when password is not set

docs/pages/configuration/dev/connections/restart-helper.mdx
=> correct python spelling

pkg/devspace/server/download.go, pkg/devspace/services/inject/inject.go, pkg/util/git/helper.go
/kind bugfix
GitHub has updated how the assets on their releases pages are loaded. Instead of being rendered with the initial HTML, they are now loaded asynchronously via JavaScript. Devspace was using the static HTML to determine the URLs to download supporting assets. This PR modifies the download URLs to rely on `https://github.com/loft-sh/devspace/releases/download/[VERSION]/[ASSET]` style download URLs.
Fixed an issue where DevSpace could not download the DevSpace UI and the `devspacehelper`
=> fix: update asset download urls

pkg/devspace/devpod/devpod.go
Fixed an issue where DevSpace would wrongly select a pod when a container is specified
=> refactor: improve dev pod selection

Dockerfile, dist/npm/index.js, dist/npm/package-lock.json, dist/npm/package.json, docs/pages/_partials/install-cli.mdx
/kind bugfix
Latest version discovery used by our npm install scripts does not work with recent updates to GitHub. This refactors the scripts to work with redirect urls on `/releases/latest`
Fixed an issue where installing DevSpace via `npm` would fail.
=> fix: update npm install script to use redirect URL

pkg/devspace/config/loader/loader.go, pkg/devspace/config/loader/variable/predefined_variable.go, pkg/devspace/config/loader/variable/resolver.go, pkg/devspace/pipeline/engine/basichandler/commands/is_in.go, pkg/devspace/pipeline/engine/basichandler/handler.go
Add builtin `DEVSPACE_PROFILES` variable containing all enabled profiles
Add `DEVSPACE_PROFILES` variable
For now it is still a draft because the variable is an array and is "converted" into a list of string with extra `[` and `]`. Need to figure out how to resolve that
=> Add DEVSPACE_PROFILES variable and is_in command

devspace-schema.json, docs/pages/configuration/_partials/v2beta1/deployments/updateImageTags.mdx, docs/pages/configuration/_partials/v2beta1/dev/containers/sync/onUpload/execRemote.mdx, docs/pages/configuration/_partials/v2beta1/dev/containers/sync/onUpload_reference.mdx, docs/pages/configuration/_partials/v2beta1/dev/containers/sync_reference.mdx, docs/pages/configuration/_partials/v2beta1/dev/sync/onUpload/execRemote.mdx, docs/pages/configuration/_partials/v2beta1/dev/sync/onUpload_reference.mdx, docs/pages/configuration/_partials/v2beta1/dev/sync_reference.mdx, docs/schemas/config-openapi.json, pkg/devspace/config/versions/latest/schema.go
resolves N/A
Fixed an issue where DevSpace docs showed some deprecated configs on the config reference docs
N/A
=> docs: hide deprecated printLogs & remoteExec configs in docs

pkg/devspace/config/loader/variable/testing/with_default_value/devspace.yaml, pkg/devspace/config/loader/variable/testing/without_default_value/devspace.yaml, pkg/devspace/config/loader/variable/undefined_variable.go, pkg/devspace/config/loader/variable/undefined_variable_test.go, pkg/util/log/stream_logger.go, pkg/util/survey/survey.go
/kind bugfix
resolves #2266
Consider default value even if it was set to empty in non-terminal devspace execution
=> Consider default value even if it was set to empty in non-terminal devspace execution

docs/pages/configuration/profiles/README.mdx
resolves #2313
Clean documentation regarding `use profile` command
=> docs: remove use profile command

docs/pages/_partials/install-cli.mdx, docs/versioned_docs/version-4.x/getting-started/installation.mdx, docs/versioned_docs/version-5.x/fragments/install-cli.mdx
Replace `chmod`/`mv` commands in install docs with single `install -c` command.
Simplified install docs.
Requested by @FabianKramm
=> docs: replace chmod/mv with install command

pkg/devspace/dependency/util/util.go, pkg/devspace/dependency/util/util_test.go
/kind feature
resolves #2323
Added a new feature where devspace will use ssh if https fails and vice versa while pulling dependency.
=> feat: fallback to ssh if https doesn't work and vice versa

pkg/devspace/pullsecrets/init.go
/kind bugfix
resolves #2324
The `wincred` credential store returns an empty `username` when resolving credentials. Because of this, we skip creating the pull secret since we don't have complete credentials.
The solution is to provide a username of `00000000-0000-0000-0000-000000000000` when using ACR, [according to their docs](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli#az-acr-login-with---expose-token). This issue is specific to the `wincred` credential store.
Fixed an issue where DevSpace would not create a pull secret …
=> fix: use registry token for pull secrets

pkg/devspace/dependency/util/util.go, pkg/util/git/git.go
/kind bugfix
resolves #2323 
Fixed an issue where DevSpace hangs till git credentials are not provided.
=> fix: fallback to ssh if https fails and vice versa

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md
Should fix automatically assigned labels for the new issues.
If you look at the recently reported issues they are missing the "kind" label (except where added manually).
N/A
I am not sure why it stopped working, I just copied the config from our vcluster repo.
=> Fix issue template labels

pkg/devspace/build/builder/docker/docker.go, pkg/devspace/pullsecrets/init.go, pkg/devspace/pullsecrets/util.go
/kind bugfix
resolves #2365
Fixed an issue where DevSpace always attempts a registry authentication call. Azure Container registries use a different authentication method, and no longer responds correctly to `/auth` requests. They [encourage users to use `az acr login` to refresh their credentials instead](https://learn.microsoft.com/en-us/azure/container-registry/container-registry-authentication?tabs=azure-cli#individual-login-with-azure-ad).
DevSpace will log a message reminding users that they can …
=> fix: skip /auth call for ACR registries

CONTRIBUTING.md
resolves #2382 
Add devspacehelper build steps in Contributing.md 
=> Add devspacehelper build details

pkg/devspace/build/build.go, pkg/devspace/build/builder/buildkit/buildkit.go, pkg/devspace/build/builder/docker/docker.go, pkg/devspace/build/registry/util.go, pkg/devspace/build/registry/util_test.go, pkg/devspace/docker/client.go, pkg/devspace/kubectl/util.go
/kind bugfix
- Resolves an issue where the local registry was used for vclusters on Minikube, Docker Desktop, and KinD clusters
- Refactored a few locations that were checking for Minikube that would have failed for vcluster & minikube
- Allow local registry to be used with Minikube when explicitly enabled
Fixed an issue where DevSpace local registry was incorrectly used for virtual clusters on local Kubernetes clusters
Previously the local registry could never be used with minikube. These changes allow the user to opt in to the local registry with …
=> Skip local registry use for vclusters on local kubernetes clusters

pkg/devspace/context/context.go
Allows users to use the tilde `~` to refer to their home directory in sync path, e.g.:
```
sync:
- path: ~/.m2/settings.xml:./bindings/maven/settings.xml
file: true
```
Added support for the tilde `~` to refer to the home directory in the sync path.
I am surprised that this was not implemented before. Maybe there is a good reason for not supporting this?
=> feat: support "~" (home) at the start of sync path

docs/versioned_docs/version-5.x/configuration/images/buildkit.mdx
A user was attempting to manage the BuildKit Daemon using [instructions from this repo](https://github.com/moby/buildkit/tree/master/examples/kubernetes#deployment--service) in order to increase replicas and use a Horizontal Pod Autoscaler. However, the `buildctl` command is not supported by DevSpace, and our docs were misleading in that the Deployment created for the BuildKit Daemon would match the name given in the `inCluster.name` option.
Instead, this name is passed to `docker buildx create --driver kubernetes` which creates a deployment with a different name, usually `${inCluster.name}0`. There is not an …
=> docs: remove incorrect statement about BuildKit deployment name

ui/src/components/views/Commands/Commands/CommandsList/CommandsList.tsx, ui/src/components/views/Logs/TerminalCache/TerminalCache.tsx, ui/src/lib/rest.ts
resolves #2407
Fixed an issue where DevSpace would attempt to connect to non-SSL web sockets when served over SSL
=> fix: use 'wss' protocol when ui is loaded via 'https'

cmd/run_pipeline.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/run_dependency_pipelines.go, pkg/devspace/pipeline/pipeline.go
/kind feature
resolves #2380 
Added global flag `--sequential-dependencies` which deploys dependencies sequentially.
=> feat: add global flag for running dep sequentially

pkg/devspace/build/build.go, pkg/devspace/build/registry/deployment.go, pkg/devspace/build/registry/local_registry.go, pkg/devspace/build/registry/options.go, pkg/devspace/build/registry/service.go, pkg/devspace/build/registry/statefulset.go
/kind bugfix
resolves #2411
Fixes ENG-603
Fixed an issue where DevSpace could not reuse a local registry if required by multiple dependencies
This is a basic fix, where the registry is matched by name. If dependencies use different registry configurations, then the last one wins.
=> fix: port forward to local registry with multiple dependencies

cmd/root.go, e2e/tests/imports/imports.go, e2e/tests/imports/testdata/conditional/devspace.yaml, e2e/tests/imports/testdata/conditional/import.yaml, pkg/devspace/config/loader/imports.go, pkg/devspace/config/loader/loader.go, pkg/devspace/config/loader/parser.go, pkg/devspace/config/loader/variable/resolver.go, pkg/devspace/config/loader/variable/types.go, pkg/devspace/config/versions/versions.go, pkg/devspace/generator/language_test.go, pkg/devspace/pipeline/engine/engine.go
/kind bugfix
resolves #2408 
Fixed an issue where DevSpace was not using imported variables in defining another variable in main devspace.yaml
=> fix: Imported variables are not used in other variables

pkg/devspace/services/proxycommands/commands.go, pkg/devspace/services/ssh/config.go, pkg/devspace/services/ssh/keys.go
/kind bugfix
resolves #2435 
Fixed an issue where DevSpace use to generate ssh keys with RSA and now the SHA-1 is deprecated this generated keys were having trouble in the authentication.
=> fix: generate keys using ecdsa instead of rsa

pkg/devspace/build/builder/buildkit/buildkit.go, pkg/devspace/build/builder/docker/docker.go
Added missing image tag to `ShouldRebuild()`
to detect that an image is already present in the
registry and to prevent constant rebuilds.
Closes #2442
/kind bugfix
resolves #2442
Fixes ENG-722 
Fixed an issue where DevSpace was always rebuilding images for local registry even if it should not.
=> fix: Prevent constant rebuilding with local registry

docs/pages/_partials/kustomize-options-kustomizeArgs.mdx
Either add a note like this _or_ replace the shown kustomizeArgs values with ones that _do_ work? I tried the manifest as shown and they break the deploy since that is not a valid kustomize command (at least not with the _latest_ version of it, perhaps they used to work):
`create_deployments: error deploying app: error executing 'kustomize build ./k8s/base --timeout 30s --grace-period 30': Error: unknown flag: --timeout`
Text edit to clarify
Updated docs
=> Perhaps add a note that the sample values break a deploy

docs/pages/configuration/variables.mdx
Adds missing documentation about forcing variables to strings using `$!{MY_VAR}`.
Several users have been tripped up by this recently.
=> docs: add note about forcing variables to string

dist/npm/index.js
/kind bugfix
Fixes ENG-822
Fixed an issue where DevSpace release process would use versions with the wrong format for npm publish and downloading of assets.
This would cause the latest version to be installed even when specifying a version using `npm install -g devspace@[version]`
=> fix: sanitize versions passed from github actions

docs/pages/configuration/_partials/v2beta1/images/kaniko/generateName.mdx, docs/pages/configuration/_partials/v2beta1/images/kaniko_reference.mdx, docs/pages/configuration/images/build-engines/kaniko.mdx, pkg/devspace/build/builder/kaniko/build_pod.go, pkg/devspace/config/versions/latest/schema.go
/kind feature
resolves #2475 
Added `generateName` option for kaniko build pod that allows users to have custom kaniko pod names
Closes ENG-823
=> feat: custom kaniko pod names

e2e/tests/localregistry/localregistry.go, helper/cmd/proxycommands/configure.go, helper/cmd/proxycommands/run.go, pkg/devspace/build/build.go, pkg/devspace/build/registry/util.go, pkg/devspace/build/registry/util_test.go, pkg/devspace/services/proxycommands/commands.go
=> refactor: disable local registry in some cases

pkg/devspace/services/podreplace/builder.go, pkg/devspace/services/ssh/config.go
=> fix: add ssh config quotes

pkg/devspace/config/remotecache/loader.go
/kind bugfix
resolves #2470
Fixes ENG-802
Fixed an issue where DevSpace commands would fail when the selected Kubernetes cluster is unavailable
=> Section commands such as devspace run [command] do not work when the k8s cluster is unavailable

.gitignore, e2e/tests/deploy/deploy.go, e2e/tests/deploy/testdata/kubectl_inline_manifest/devspace.yaml, examples/inlineManifest/.dockerignore, examples/inlineManifest/devspace.yaml, examples/inlineManifest/devspace_start.sh, pkg/devspace/config/loader/loader_test.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/validate.go, pkg/devspace/deploy/deployer/kubectl/kubectl.go, pkg/devspace/deploy/deployer/kubectl/kubectl_test.go
/kind feature
This should make possible to use inline manifests in `kubectl` blocks, for example:
```yaml
version: v2beta1
name: inline-manifest
vars:
IMAGE: nginx:1.14.2
deployments:
my-deployment:
kubectl:
inlineManifest: |-
apiVersion: apps/v1
kind: Deployment
metadata:
name: nginx-deployment
labels:
app: nginx
spec:
replicas: 3
selector:
matchLabels:
app: nginx
template:
metadata:
labels:
app: nginx
spec:
containers:
- name: nginx
image: ${IMAGE}
ports:
- containerPort: 80
```
=> Feature: Add support for InlineManifest blocks in Kubectl deployments

docs/pages/configuration/_partials/v2beta1/deployments/kubectl/inline_manifests.mdx, docs/pages/configuration/_partials/v2beta1/deployments/kubectl_reference.mdx, docs/pages/configuration/deployments/kubectl/README.mdx, docs/pages/configuration/deployments/kubectl/inline_manifests.mdx, docs/schemas/config-openapi.json, docs/sidebars.js
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>
Adding documentation page for the new Inline Manifest feature
=> docs: add documentation page for inline manifests. Fix ENG-652

docs/pages/configuration/runtime-variables.mdx, docs/sidebars.js, pkg/devspace/analyze/analyze_test.go, pkg/devspace/config/loader/variable/runtime/runtime_variable.go, pkg/devspace/config/versions/v1beta11/schema.go, pkg/devspace/kubectl/portforward/portforward.go, pkg/util/tomb/tomb.go
Adding back the Runtime Variables page in the docs. It is present DevSpace v5 docs but not in v6 anymore
Fixes ENG-878
=> docs: add back runtime variables page from 5.x. Fix ENG-878

e2e/tests/pullsecret/pullsecrets.go, e2e/tests/pullsecret/testdata/v1-upgrade/devspace.yaml, pkg/devspace/config/versions/v1beta11/upgrade.go, pkg/devspace/dependency/util/util_test.go, pkg/devspace/server/download.go, pkg/devspace/services/inject/inject.go
/kind bugfix
Fixes ENG-922
Fixed an issue where DevSpace no longer creates image pull secrets for all images for v1beta11 schemas
=> fix: add pull secret config for images during v5->v6 schema upgrade

pkg/devspace/build/builder/kaniko/kaniko.go, pkg/util/progressreader/progressreader.go
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>
/kind feature
Fix #2496
Fix ENG-872 
Added file progress while doing file uploads
This should ensure the user will receive a feedback during long running transfer oprations
=> feat: add file upload progress

cmd/run_pipeline.go, e2e/tests/pipelines/pipelines.go, e2e/tests/pipelines/testdata/flags/dep1.yaml, e2e/tests/pipelines/testdata/flags/devspace.yaml, pkg/devspace/context/values/values.go
/kind bugfix
resolves #2461
Fixes ENG-761
Fixed an issue where dependencies pipelines could not access command flags using `get_flag` 
No docs update needed
=> fix: make command flags available everywhere for get_flags

cmd/cleanup/images.go, pkg/devspace/build/builder/buildkit/buildkit.go, pkg/devspace/build/builder/docker/docker.go, pkg/devspace/build/builder/helper/helper.go, pkg/devspace/build/create_builder.go, pkg/devspace/build/localregistry/util.go, pkg/devspace/configure/image.go, pkg/devspace/configure/manager.go, pkg/devspace/docker/client.go, pkg/devspace/kubectl/util.go, pkg/util/factory/factory.go, pkg/util/factory/testing/factory.go
Signed-off-by: Russell Centanni <russell.centanni@gmail.com>
/kind bugfix
resolves #1932 
fixes ENG-129
Fixed an issue where DevSpace does not detect minikube clusters created using profiles:`minikube start -p ${NOT_MINIKUBE}`
This is a work in progress.
=> fix: improve detection of minikube clusters

cmd/list/ports.go
/kind bugfix
resolves #2557
Fixed an issue where DevSpace doe not list forwarded ports when one entry in the dev section has none configured
=> fix: continue even if a dev config has no Ports when running list ports

docs/pages/cli/devspace_list_ports.md, docs/pages/configuration/dev/modifications/patches.mdx, pkg/devspace/services/podreplace/builder.go
Sync may not work if the container SecurityContext enables ReadOnlyRootFilesystem.
So let's do an Implicit Patch to remove this, and leave user's `devspace.yaml` less cluttered
/kind bugfix
resolves #2572 
Closes ENG-1055
=> fix: add implicit patch during dev to unset readOnlyRootFilesystem when sync is enabled

e2e/tests/replacepods/replacepods.go, e2e/tests/replacepods/testdata/restart-helper/devspace.yaml, pkg/devspace/build/builder/restart/restart.go
/kind bugfix
resolves #2571 
Closes ENG=1053
With these workarounds, we get the same effect of `tail --pid` but we fix compatibility with non-GNU userlands, where non-standard flags are unsupported.
Also switch the e2e test to alpine, in order to cover this type of use-case
=> fix: make restart script compatible with non-GNU userlands

.github/workflows/check-docs.yaml, gendocs.sh
Closes ENG-1030
This will add a new Github Action that will check if we need to update auto-generated docs.
The action will simply run the `gendocs.sh` script, and if changes are detected, we inform the users in the PR using
a bot message.
Here is an example:
=> ci: add job to detect PRs that need docs update

cmd/init.go
resolves #2587
fixes ENG-1069
Fixed an issue where DevSpace init is syncing `node_modules` by default, which modifies permissions and prevents locally installed CLI modules from working correctly
While not necessarily a bug, this could trip up many first-time users who are not aware that excluding `node_modules` from syncing is usually a good idea.
=> fix: exclude node_modules during devspace init by default

pkg/devspace/config/config.go, pkg/devspace/config/loader/variable/legacy/replace.go, pkg/devspace/config/loader/variable/legacy/replace_test.go
/kind bugfix
A breaking change was made to the replace images logic. This adds tests to prevent future breaking changes.
May be related to #2573 and #2569, but needs further investigation.
Reverted a breaking change to image replace logic.
=> fix: revert #2540 and add tests to prevent future regressions

e2e/tests/hooks/hooks.go, e2e/tests/hooks/testdata/once/devspace.yaml, pkg/devspace/config/loader/variable/predefined_variable.go, pkg/devspace/config/loader/variable/resolver.go
Adds a `DEVSPACE_SPACE` variable to help migrating users from DevSpace Cloud
Adds a `DEVSPACE_SPACE` variable to help migrating users from DevSpace Cloud
Users must uninstall the [devspace-cloud-plugin](https://github.com/devspace-cloud/devspace-cloud-plugin)
=> feat: add variables to support migrating DevSpace Cloud users

e2e/tests/localregistry/testdata/local-registry-kubectl/manifests/deployment.yaml, e2e/tests/render/render.go, e2e/tests/render/testdata/helm/rendered.txt, pkg/devspace/deploy/deployer/helm/client.go
Upgrade component-chart to latest version 0.8.6
Containing the fix for #2517
=> chore: upgrade component-chart to 0.8.6

pkg/devspace/build/localregistry/local_registry.go
/kind bugfix
resolves #2603 
Closes ENG-1154
Fixed an issue where DevSpace would attempt to create the namespace for localregistry even it the namespace indeed exists.
This came out as a problem in the moment the user wasn't authorized to create namespaces, thus checking before leaping now.
=> fix: do ensureNamespace only if the namespace doesn't really exist.

pkg/devspace/hook/hook.go
/kind bugfix
resolves #2622
Fixed an issue where DevSpace would panic if a silent hook fails
=> fix: silent hook panic

pkg/devspace/deploy/deployer/helm/status.go, pkg/devspace/deploy/deployer/helm/status_test.go
/kind bugfix
resolves #2626
Fixed an issue where DevSpace would not consider the configured helm release name when showing deployment statuses.
I wonder if some work should be done to avoid the potential of two deployments being configured as having the same helm release name or whether this would be considered a user error which wouldn't happen too often anyway.
=> fix: consider helm release name when showing helm deployment status

pkg/devspace/configure/image.go
Added Validation Regex and Message to the user provided registry username
resolves #
Fixes ENG-701
Fixed an issue where DevSpace connected registry username was not checked for UpperCase letters. 
=> Added Validation Regex and Message to the user provided registry username

e2e/tests/localregistry/localregistry.go, go.mod, go.sum, pkg/devspace/config/loader/patch/patch.go, pkg/devspace/config/loader/patch/patch_test.go, pkg/devspace/deploy/deployer/kubectl/builder.go, pkg/devspace/deploy/deployer/kubectl/kubectl.go, vendor/google.golang.org/genproto/googleapis/api/httpbody/httpbody.pb.go, vendor/modules.txt
/kind bugfix
Partial resolution of #2634
Fixed an issue where DevSpace would reformat yaml when 0 patches are applied
This is only a partial fix of #2634. If there are patches, the YAML formatting issue still occurs.
go.mod & go.sum changes were only to resolve issues running `go mod tidy` locally.
Other things tried:
- detecting and setting the encoder indentation: The same defect occurs if a YAML document with 4 spaces gets passed in, for example:
```yaml
test: …
```
=> fix: avoid reformatting yaml when there are no patches to apply

.github/workflows/e2e-tests.yaml, .github/workflows/lint.yaml, .github/workflows/release.yaml, .github/workflows/unit-tests.yaml, e2e/e2e_suite_test.go, go.mod, helper/main.go, main.go
/kind bugfix
Updates go version to 1.20
Will possibly resolve:
https://nvd.nist.gov/vuln/detail/CVE-2023-24536
https://nvd.nist.gov/vuln/detail/CVE-2023-29400
Fixes ENG-1469
=> chore: upgrade to go 1.20

cmd/run.go, e2e/tests/command/command.go, e2e/tests/command/testdata/command-without-cluster/config, e2e/tests/command/testdata/command-without-cluster/devspace.yaml
fixes #2648
/kind bugfix
resolves #2648
Fixed an issue where DevSpace fails to load remote cache when running commands.
=> Devspace command fails when cluster is not required

docs/pages/configuration/functions/README.mdx
Improves docs by clarifying that custom `functions` can only be called in the `pipelines` context
=> docs: clarify where functions can be used

devspace-schema.json, docs/pages/configuration/_partials/v2beta1/name.mdx, docs/pages/configuration/imports/README.mdx, docs/schemas/config-openapi.json, e2e/tests/imports/imports.go, e2e/tests/imports/testdata/localregistry/defaults.yaml, e2e/tests/imports/testdata/localregistry/devspace.yaml, pkg/devspace/config/loader/imports.go, pkg/devspace/config/versions/latest/schema.go
/kind bugfix
resolves #2665
Fixes ENG-1686
Fixed an issue where DevSpace did not import localRegistry configuration
Added a section to the docs to describe import sections that are importable.
=> fix: add localRegistry to imported sections

docs/pages/configuration/dev/modifications/dev-image.mdx
When replacing the image of an application's container with a `devImage`, an entrypoint must be added to keep the container alive.
This is now explicit in the docs.
=> add explanation to necessary command for devimages

docs/pages/configuration/localRegistry/README.mdx
Explicitly state which build engines are supported for using `localRegistry`
=> clarify only supported build engines for localRegistry

pkg/devspace/dependency/util/util.go
/kind bugfix
resolves #2641
Fixed an issue where DevSpace deploy did not correctly use the `C:\Users\[user]\.devspace\dependencies` cached files, ending up always pulling the git repo.
- Not able to write tests for this as the test scripts dont work on windows.
- Tested locally by building devspace.exe and calling `C:\Projects\devspace-deps-fix\devspace.exe deploy --debug`
=> fix: correctly use local git repo dependencies cache

cmd/run_pipeline.go, pkg/devspace/dependency/manager.go, pkg/devspace/dependency/resolver.go
/kind bugfix
Partly solves #2641
Fixed an issue where DevSpace flag --dependency was not respected by the git repo recursive resolver
I have not ran any unit tests or e2e tests as your contribution guide and bash scripts dont work on windows.
I have tested manually by building a devspace.exe file and then tested these 3 cases standing in a repo with a complex dependency hierarchy:
1 - Normal `C:\Projects\devspace-deps-fix\devspace.exe deploy --debug`
-> Download all …
=> fix: --dependency flag is respected by dependency resolving

pkg/devspace/deploy/deployer/helm/deploy.go, pkg/devspace/deploy/deployer/helm/deploy_test.go
/kind bugfix
resolves #2525 
Fixed an issue where DevSpace would leave behind orphaned helm releases when setting a helm release name
It doesn't fully fix the use case in #2525, as the originally expected behavior doesn't play well with `devspace` currently.
However, this fix makes `devspace` avoid "orphaned" deployments lingering around.
IMO this is the behavior most people would expect, as the default is to purge all deployments associated with a project.
=> fix: remote cache key should consider helm release name

cmd/init.go, e2e/tests/ssh/ssh.go, e2e/tests/ssh/testdata/ssh-variable/devspace.yaml, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/helm/v3/client.go, pkg/devspace/pipeline/engine/basichandler/handler.go, pkg/devspace/services/ssh/ssh.go, pkg/util/log/logger.go
/kind bugfix
Fixes #2693
Fixes ENG-1886
Fixed an issue where DevSpace did not allow explicitly disabling SSH when other SSH was given.
This also enables disabling SSH via variables.
=> fix: allow SSH to be enabled and disabled via variable

helper/server/downstream.go, pkg/devspace/sync/downstream.go, pkg/devspace/sync/sync.go, pkg/devspace/sync/upstream.go
/kind bugfix
resolves #2738 
Fixed an issue where DevSpace left over orphaned GRPC connections when pods are removed.
This reduces the annoying grpc logs to 2 coming from the ping, just before the connection gets closed.
=> change: when stopping upstream/downstream, also close grpc connections

docs/pages/configuration/images/pull.mdx
resolves #2730
resovles ENG-2186
Fixed incorrect reference to `createPullSecret` in documentation.
=> docs: update incorrect createPullSecrets reference

pkg/devspace/build/build.go
Fixes #2729
Fixes ENG-2185
/kind bugfix
resolves #2729
Fixed an issue where DevSpace creates pull secrets during`devspace build` even when they are not required.
=> Devspace defaults to uploading credentials to cluster

e2e/tests/pipelines/pipelines.go, e2e/tests/pipelines/testdata/invalid_kubeconfig/dep1.yaml, e2e/tests/pipelines/testdata/invalid_kubeconfig/devspace.yaml, e2e/tests/ssh/ssh.go
/kind test
Add regression test for nil pointer on invalid kubeconfig
=> tests: add regression tests for nil pointer on invalid kubeconfig

hack/build-all.bash
This is a mitigation for https://github.com/devspace-sh/devspace/issues/2448#issuecomment-1851824126
/kind bugfix
resolves #2448 
Disables upx binary compression for devspace-helper on linux/arm64. It causes crashes when >500 env vars or flags are present (combined).
=> fix: disable upx for linux/arm64

helper/util/restart_linux.go
/kind bugfix
resolves #2788
The helper restart command would wait for 2 microseconds (2000 nanoseconds, supposedly meant to be 2 seconds) between sending SIGINT and SIGKILL to the subcommand. Changed this to send SIGINT, SIGTERM and SIGKILL with five seconds in between, checking for process termination.
=> restart helper: give container process some time to shutdown

devspace-schema.json, docs/hack/config/schemas/main.go, docs/schemas/config-openapi.json
**What issue type does this pull request address?** (keep at least one, remove the others)
/kind bugfix
**What does this pull request do? Which issues does it resolve?** (use `resolves #<issue_number>` if possible)
resolves #2770
resolves ENG-2531
Fixed an issue where DevSpace json schema incorrectly shows variables and expressions as invalid.
May also need to add variable expressions, however these cannot be used for structural changes.
=> fix: allow config expressions in devspace-schema.json

docs/README.md, docs/hack/functions/main.go, docs/pages/configuration/_partials/functions/group_checks.mdx, docs/pages/configuration/_partials/functions/group_checks_global.mdx, docs/pages/configuration/_partials/functions/group_checks_pipeline.mdx, docs/pages/configuration/_partials/functions/is_dependency.mdx, docs/pages/configuration/_partials/functions/is_empty.mdx, docs/pages/configuration/_partials/functions/is_equal.mdx, docs/pages/configuration/_partials/functions/is_in.mdx, docs/pages/configuration/_partials/functions/is_os.mdx, docs/pages/configuration/_partials/functions/is_true.mdx, gendocs.sh
Moves `is_dependency` from the "Global Functions" section of the [built-in functions list](http://localhost:8000/docs/configuration/functions/#built-in-functions) to the "Pipeline-Only Functions" section (`is_dependency` is pipeline-only).
Updated classification of `is_dependency` in documentation.
=> docs: move is_dependency to correct function group

pkg/devspace/build/builder/kaniko/build_pod.go
/kind bugfix
resolves #2810
resolves ENG-2940
Fixed an issue where DevSpace kaniko builds fail with the ECR credential helper.
Upgrading the image fixed the user's issue.
=> fix: update kaniko build image

docs/pages/configuration/dependencies/README.mdx
Resolves ENG-2956
Removed references to an outdate command in the documentation
=> docs: remove reference to outdated command

cmd/run.go
/kind bugfix
resolves #2837
resolves DSP-6
Fixed an issue where DevSpace would always prompt on the 'default' namespace when running commands.
=> fix: honor --no-warn and --switch-context flags when running commands

docs/pages/configuration/_partials/v2beta1/dev/containers/sync/initialSync.mdx, docs/pages/configuration/dev/connections/file-sync.mdx, e2e/tests/sync/sync.go, e2e/tests/sync/testdata/sync-initial-disabled/devspace.yaml, e2e/tests/sync/testdata/sync-initial-disabled/node_modules/nodemon/nodemon.js, e2e/tests/sync/testdata/sync-initial-disabled/syncme/file.txt, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/v1beta10/schema.go, pkg/devspace/config/versions/v1beta11/schema.go, pkg/devspace/config/versions/v1beta7/schema.go, pkg/devspace/config/versions/v1beta8/schema.go, pkg/devspace/config/versions/validate.go, pkg/devspace/sync/initial.go, pkg/devspace/sync/sync.go
/kind feature
Partially resolves #1218 adding support to disable completely the initial sync
Enhance the configuration capabilities of DevSpace to enable the possibility of disabling the initial sync, similar to how you can currently disable the upload or download.
There are use cases where syncing is required only for files changed after the development or sync process has been initiated, rather than fully synchronizing the remote or local …
=> disableInitialSync feature flag

.golangci.yml
/kind bugfix
Part of DSP-5
Fixed an issue where DevSpace builds failed due to deprecated linters.
=> chore: update golangci-lint configuration to remove deprecated linters

pkg/devspace/configure/deployment.go
/kind bugfix
Resolves #2838. See that issue for details.
New error message displayed when following the repro steps documented in the issue:
```
~/helm-test > helm create foo
Creating foo
~/helm-test > ls
foo
~/helm-test > cd foo
~/helm-test/foo > l
charts/  Chart.yaml  templates/  values.yaml
~/helm-test/foo > cd ..
~/helm-test > alias devspace=/home/matt/code/github.com/mattwelke/devspace/devspace
~/helm-test > devspace init
%########%      
%###########%       ____                 _____                      
%#########%    |  _ \   ___ __   __ / ___/  ____    ____   ____ ___ 
%#########%    | | | | / _ \\ \ / / \___ \ |  _ \  / _ …
```
=> fix: better error message for invalid Helm Chart path during init

pkg/devspace/build/builder/localregistry/build.go
/kind bugfix
resolves #
avoid to return a nil err
fix a bug
I have an idea to detect code that returns a non-relevant nilness error bug. I checked the top 1000 GitHub Go repositories and found this, all result listed in https://github.com/alingse/sundrylint/issues/4
=> fix: check `update.Error != nil` but return a nil value error `err`

pkg/devspace/configure/image.go
/kind bugfix
resolves #DSP-101
=> fix: Removes negative lookahead from regex

helper/util/conn.go, pkg/devspace/services/sync/controller.go
/kind bugfix
resolves #DSP-137
See: [here](https://github.com/grpc/grpc-go/blob/v1.74.2/resolver/resolver.go#L72)
=> Removes call to SetDefaultScheme, which is not thread safe.
