devspace-sh/devspace

cmd/up.go, pkg/devspace/clients/kubectl/client.go
- show last line of kaliko output on fail
=> - improve output

docs/.devspace/.gitignore, pkg/devspace/clients/kubectl/client.go
- write portforwarding logs only to one file
=> - correct gitignore

cmd/init.go, cmd/up.go, pkg/devspace/config/v1/kubernetes.go, pkg/devspace/generator/generator.go, pkg/devspace/sync/sync_config_test.go, pkg/devspace/sync/util.go, pkg/util/jujuerr_test.go, pkg/util/log/stdout_logger.go, pkg/util/paramutil/param_test.go, pkg/util/processutil/pipe.go, pkg/util/randutil/rand_test.go
Also the first golint errors are fixed
=> This time the files are overwritten by the command "gofmt -s -w".

cmd/add.go, cmd/list.go, cmd/remove.go
- devspace add port (Resolve #94)
- devspace add sync (Resolve #92)
=> Implement:

pkg/devspace/image/build.go
**What type of pull request is this?** (keep at least one, remove the others)  
/kind bug fix  
/king enhancement  
/kind feature  
/kind documentation  
resolves #
=> Override image tag also during build

cmd/deploy.go, cmd/init.go, pkg/devspace/cloud/update.go, pkg/devspace/kubectl/client.go
/kind bug
/king enhancement
/kind feature
resolves #
=> Fix issue with using the wrong cloud target on devspace up

PULL_REQUEST_TEMPLATE.md, cmd/deploy.go, cmd/init.go, cmd/up.go, docs/docs/configuration/config.yaml.md, pkg/devspace/config/v1/deployments.go, pkg/devspace/deploy/helm/client.go, pkg/devspace/deploy/interface.go, pkg/devspace/deploy/kubectl/kubectl.go, pkg/devspace/deploy/util.go
allows users to specify a devOverwrite parameter for deployments with helm
yes, new config option in devSpace.deployments[].helm.devOverwrite
no
=> Up overwrite

pkg/devspace/image/build.go
=> Fixes #336

cmd/down.go, cmd/status.go, pkg/devspace/deploy/helm/client.go, pkg/devspace/deploy/interface.go, pkg/devspace/deploy/kubectl/kubectl.go, pkg/devspace/deploy/util.go
/kind bug
/kind feature
resolves #
=> Refactor dev overwrite

README.md, docs/website/siteConfig.js, pkg/devspace/kubectl/util.go
=> update docs page url

pkg/devspace/config/configutil/get.go, pkg/devspace/config/configutil/load.go
=> Resolve #350

cmd/enter.go, cmd/up.go, docs/docs/cli/enter.md, docs/docs/cli/list.md, docs/docs/cli/up.md, docs/docs/configuration/config.yaml.md, examples/kaniko-minikube/.devspace/config.yaml, examples/minikube/.devspace/config.yaml, examples/offline-development/.devspace/config.yaml, examples/php-mysql-example/.devspace/config.yaml, examples/quickstart-kubectl/.devspace/config.yaml, examples/quickstart/.devspace/config.yaml, pkg/devspace/builder/kaniko/kaniko.go, pkg/devspace/config/v1/image.go, pkg/devspace/configure/registry.go, pkg/devspace/image/build.go, pkg/devspace/registry/init.go, pkg/devspace/registry/registry.go, pkg/devspace/registry/util.go
=> Refactoring of create image pull secrets for image registries

pkg/devspace/services/terminal.go
/kind bug
use default service when running `devspace up` without -s
=> use default service for devspace up

docs/docs/configuration/config.yaml.md
fixes issue with config example in docs
=> fix config example

cmd/add.go, cmd/deploy.go, cmd/list.go, cmd/remove.go, cmd/up.go, pkg/devspace/configure/package.go, pkg/devspace/configure/packagedefaults.go, pkg/devspace/configure/registry.go, pkg/devspace/helm/tiller.go, pkg/devspace/sync/downstream.go, pkg/util/log/discard_logger.go, pkg/util/log/file_logger.go, pkg/util/log/log.go, pkg/util/log/logger.go, pkg/util/log/stdout_logger.go
/kind feature
upgrade tiller version
fix several issues with devspace add/remove package
add re-deploy option to devspace add/remove package
improve output
no
=> improve devspace add/remove package

cmd/reset.go, pkg/devspace/cloud/config.go, pkg/devspace/cloud/delete.go
=> Delete devspace in the cloud

cmd/init.go, cmd/up.go
/kind feature
**What is this pull request for? Which issues does it resolve?** 
`resolves #322 ` 
**Does this pull request has user-facing changes?** 
new flags in devspace up to answer all question by the default
nothing
flags naming, I offer to be changed to “-d/ —default”. because some default answers is not yes.
=> Add --yes/-y flags to devspace up #322

pkg/devspace/configure/packagedefaults.go
set package defaults for popular databases
=> set package default values for mysql, mariadb, influxdb, monogodb, redis

cmd/reset.go
/kind bug
/kind feature
resolves #
=> Change question and fix deletion of kube context

cmd/enter.go, cmd/up.go, pkg/devspace/services/terminal.go
/kind feature
makes up.go testable
no
no
Some method headers in up.go changed
=> Prepare up.go for testing

cmd/init.go, pkg/devspace/configure/registry.go
/kind feature
The questions from the init-command are now individually answerable with api-exclusive flags
no
no
The method head of the Image-method in registry.go changed
=> Add individual answer flags

docs/docs/configuration/config.yaml.md
documentation for config option devSpace.services
=> add documentation for DevSpace services

pkg/devspace/config/configutil/merge.go
resolves issues with overwriting arrays in config.yaml via overwrite.yaml => now, arrays will be entirely overwritten as it is expected
no
=> fix overwrite for arrays in config

cmd/deploy.go, cmd/down.go, cmd/enter.go, cmd/init.go, cmd/list.go, cmd/reset.go, cmd/up.go, pkg/devspace/config/configutil/get.go, pkg/devspace/config/configutil/make.go, pkg/devspace/config/configutil/save.go, pkg/devspace/configure/port.go, pkg/devspace/configure/sync.go, pkg/devspace/deploy/util.go, pkg/devspace/services/port_forwarding.go, pkg/devspace/services/sync.go
/kind bug
Fix an issue with the merge algorithm. Add devspace enter --config / --config-overwrite
=> Improve config overwrite

cmd/init.go, cmd/up.go
improves output for devspace init
=> Improve init output

cmd/up.go, pkg/devspace/deploy/helm/client.go, pkg/devspace/docker/client.go, pkg/devspace/kubectl/util.go, pkg/devspace/registry/init.go
=> Fix issue with docker and clusterrolebinding

docs/docs/advanced/rbac.md
=> Fix documentation for permissions

pkg/devspace/helm/tiller.go
=> Delete tiller if deployment has issues & improve delete tiller

docs/docs/configuration/config.yaml.md, docs/docs/configuration/overwrite.yaml.md
=> Improve documentation

cmd/down.go, cmd/reset.go
/kind feature
Yes new --deployment flag for the devspace down command
=> New devspace down --deployment flag

cmd/init.go, pkg/devspace/helm/tiller.go
=> Fix issue with wrong tiller deployment on devspace up

pkg/devspace/configure/deployment.go
/kind bug
resolves #422 
No
No
None
=> fixed add deployment

cmd/add.go, cmd/remove.go, pkg/devspace/config/v1/devspace.go, pkg/devspace/configure/image.go, pkg/devspace/configure/port.go, pkg/devspace/configure/service.go, pkg/devspace/configure/sync.go
/kind feature
resolves #423 
The user can add and remove services and images via command
no
small fixes in comments and the methods AddPort, AddSync and RemoveSync
=> Add and remove for images and services implemented

pkg/devspace/configure/image.go, pkg/devspace/configure/service.go, pkg/devspace/configure/sync.go
/kind bug
fixes some nil pointers in the add-command
no
no
nothing
=> Fixed nil pointers in add-commands

pkg/devspace/builder/kaniko/kaniko.go
/kind bug
resolves #391 
no
no
nothing
=> Add BuildArgs to kaniko BuildCmd

docs/website/siteConfig.js, docs/website/static/css/header.css
/kind bug
/kind feature
resolves #
=> header links

docs/website/siteConfig.js
/kind bug
/kind feature
resolves #
=> fixed doc links

.travis.yml, pkg/devspace/config/configutil/get.go
Update travis.yaml to devspace-cloud/devspace
=> Cloud refactor

docs/pages/images/pull-secrets.md
çhanged "Devspace.cli automatically creates and managed" to "Devspace.cli automatically creates and manages"
no
no
=> fix one word usage

docs/website/static/css/header.css
/kind bug
/kind feature
resolves #
=> header centered and larger

docs/website/static/css/header.css
/kind bug
/kind feature
resolves #
=> header centered + fix

docs/website/siteConfig.js, docs/website/static/css/header.css
/kind bug
/kind feature
resolves #
=> header change

docs/website/siteConfig.js, docs/website/static/css/header.css
Reverts devspace-cloud/devspace#487
=> Revert "header change"

pkg/devspace/deploy/kubectl/kubectl.go, pkg/devspace/kubectl/client.go, sync/stub/main.go
=> Fix nil pointer & improve kubectl error message

pkg/devspace/sync/downstream.go, pkg/devspace/sync/tar.go, pkg/devspace/sync/upstream.go, sync/server/downstream.go, sync/server/tar.go, sync/server/upstream_test.go
Small improvements in sync functionality.
=> Sync improvements

pkg/devspace/cloud/login.go
This pull request adds a log message during the login stage, to enable the user to manually navigate to the correct page.
=> Print login domain during login

cmd/cleanup/cleanup.go, cmd/cleanup/images.go, cmd/deploy.go, cmd/dev.go, cmd/root.go, docs/pages/image-building/cleanup.md, docs/pages/image-building/specification.md, docs/pages/workflow-basics/debugging/sync.md, docs/website/sidebars.json, docs/website/static/css/nav.css, examples/README.md, pkg/devspace/config/configutil/load.go, pkg/devspace/config/configutil/save.go, pkg/devspace/deploy/helm/deploy.go, pkg/devspace/deploy/kubectl/kubectl.go, pkg/devspace/deploy/kubectl/kubectl_test.go, pkg/devspace/deploy/kubectl/walk/walk.go, pkg/devspace/deploy/kubectl/walk/walk_test.go, pkg/devspace/docker/images.go, pkg/devspace/generator/component.go, pkg/devspace/generator/component_test.go, pkg/devspace/generator/language.go, pkg/devspace/services/port_forwarding.go, pkg/devspace/services/sync.go, pkg/devspace/sync/sync.go, pkg/devspace/upgrade/upgrade.go
This pull requests implements the following:
- Refactoring of the walk package, function now returns an error
- Implement `devspace cleanup images`
- Print recommendation to run devspace cleanup images if docker image build error includes no space left on device
- Docs page for `devspace cleanup images`
=> Cleanup images

docs/website/static/css/layout.css
/kind bug
/kind feature
resolves #
=> fixed issue

docs/pages/cloud/clusters/access.md, docs/pages/cloud/clusters/connect.md, docs/pages/cloud/clusters/limits.md, docs/pages/cloud/clusters/users.md, docs/pages/cloud/domains/workflow.md, docs/pages/cloud/spaces/domains.md, docs/pages/cloud/spaces/resource-limits.md
Fix some minor documentation issues
=> Fix some documentation issues

docs/.gitignore, docs/website/README.md, docs/website/core/Footer.js, docs/website/package.json
fixes issues related to external libraries regarding search, chat etc.
=> Improve docs

docs/pages/cloud/domains/certificates.md, docs/pages/configuration/reference.md, docs/pages/deployment/components/configuration/service.md, docs/pages/deployment/components/configuration/volumes.md, docs/pages/deployment/components/containers/environment-variables.md, docs/pages/deployment/components/containers/image.md, docs/pages/getting-started/installation.md, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/component/component.go, pkg/devspace/deploy/helm/deploy_test.go, pkg/devspace/deploy/util/util_test.go
Allows to specify `externalIPs` array for component deployments
=> Component external ips

pkg/devspace/cloud/graphql.go, pkg/devspace/watch/watch_test.go, pkg/util/log/discard_logger.go, pkg/util/log/log.go
Changes:
- Implement test for watch package
=> Implement watch test

cmd/init.go
Init command will skip connect cluster question if default provider is an on-premise DevSpace Cloud
=> Alter init command based on default provider

docs/website/.npmrc, docs/website/core/Footer.js, docs/website/package.json, docs/website/static/js/tag-manager.js
/kind bug
/kind feature
resolves #
=> fix npm issues with netlify and private registry

pkg/devspace/cloud/login.go
resolves #612 => This could be solved even nicer, e.g. gcloud directly generates a key and displays it, so users can directly copy it after logging in. But for now, this is a working solution which only requires to click 2 additional buttons before being able to copy an access key. That should be acceptable for now and is already much better than the current behavior.
Yes. The cloud login asks for an access key now if the user does not have a browser …
=> resolves #612

dist/npm/index.js, dist/npm/package.json
/kind bug
bug within npm install script
no
no
=> fix issues with npm install script

.gitignore, .travis.yml, cmd/dev.go, cmd/enter.go, cmd/list/deployments.go, go.mod, pkg/devspace/services/attach.go, pkg/devspace/services/terminal.go, scripts/coverage.bash, vendor/github.com/docker/cli/cli/debug/debug.go, vendor/modules.txt
=> Implement #621

cmd/dev.go, cmd/enter.go, pkg/devspace/services/attach.go, pkg/devspace/services/terminal.go
=> Implement #614

cmd/deploy.go, pkg/devspace/docker/client.go
Changes:
- Fix docker issue described in #630
=> Fix maximum support api version issue

pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/component/component.go
resolves #635
Yes, updates config to the new capabilities for component deployments as stated in #635
No
@FabianKramm - do you want to bump the config version for this?
=> update config after resolving #635

examples/dynamic-config/devspace-configs.yaml, pkg/devspace/config/configs/schema.go, pkg/devspace/config/configutil/get.go, pkg/devspace/config/configutil/load.go, pkg/util/vars/parse.go, pkg/util/vars/parse_test.go
Changes:
- Implements #637 (Source config option, escaping of variables & same naming for environment variables and config variables)
- Fixes issue where multiple vars for a single value were not correctly parsed
=> Add var source and improve var parsing

pkg/devspace/config/configutil/configs.go, pkg/devspace/config/configutil/get.go, pkg/devspace/config/configutil/load.go, pkg/devspace/config/generated/config.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/dependency/dependency.go, pkg/devspace/dependency/dependency_test.go, pkg/devspace/dependency/resolver.go, pkg/devspace/dependency/resolver_test.go, pkg/devspace/generator/language.go, pkg/util/git/git.go
Changes:
- Added subPath option to define a sub git repository path (#649)
- Use credential helper for git if possible (#648)
- Fixed bug where a branch wasn't correctly checked out (#647)
- Fixed bug where dependency config option would cause a panic
- Fixed an issue where multiple definitions of the same repository but with a different branch, tag or revision would be treated the same.
=> Dependencies: git enhancements

cmd/init.go, pkg/devspace/config/configutil/save.go
/kind bug
prevents fatal when running `devspace init` in v4 beta1
=> fix fatal that occurs when running devspace init

cmd/connect/cluster.go, cmd/dev.go, cmd/open.go, docs/pages/cli/commands/devspace_connect_cluster.md, docs/website/versioned_docs/version-v3.5.18/cli-commands/connect/cluster.md, docs/website/versioned_docs/version-v4.0.0/cli/commands/devspace_connect_cluster.md, pkg/devspace/cloud/cluster.go
- improve command-line output
- remove ingress tls section from devspace open
=> Improve output

cmd/dev.go, dist/npm/index.js, dist/npm/package-lock.json, dist/npm/package.json
Prevents npm to ask for deleting global DevSpace config and cache folder when a user runs `npm update` or `npm up`.
This question should only be asked when the user runs `npm uninstall` or `npm un`.
=> Improve npm upgrade

docs/website/static/css/content.css, docs/website/static/js/onpage-nav.js
=> improve docs styling

cmd/add/provider.go
Changes:
- trim right slash on add provider
=> Trim slash

pkg/devspace/kubectl/client.go
=> clarify warning

docs/website/siteConfig.js
=> add blog link

docs/pages/cli/configuration/reference.md, docs/pages/cli/deployment/components/configuration/service.md, docs/pages/cli/development/workflow-basics.md, docs/pages/cli/getting-started/development.md, docs/pages/cli/image-building/configuration/overview-specification.md, docs/pages/cli/image-building/workflow-basics.md, docs/website/sidebars.json, docs/website/versioned_docs/version-v3.5.18/deployment/components/configuration/service.md, docs/website/versioned_docs/version-v4.0.0/cli/configuration/reference.md, docs/website/versioned_docs/version-v4.0.0/cli/deployment/components/configuration/service.md, docs/website/versioned_docs/version-v4.0.0/cli/development/workflow-basics.md, docs/website/versioned_docs/version-v4.0.0/cli/getting-started/development.md, docs/website/versioned_docs/version-v4.0.0/cli/image-building/configuration/overview-specification.md, docs/website/versioned_docs/version-v4.0.0/cli/image-building/workflow-basics.md, docs/website/versioned_docs/version-v4.0.1/cli/development/workflow-basics.md, docs/website/versioned_docs/version-v4.0.1/cli/getting-started/development.md, docs/website/versioned_docs/version-v4.0.1/cli/image-building/configuration/overview-specification.md, docs/website/versioned_docs/version-v4.0.2/cli/configuration/reference.md, docs/website/versioned_sidebars/version-v4.0.0-sidebars.json
=> fix broken links

cmd/init.go, cmd/open.go, pkg/devspace/configure/image.go
=> Improve output for `devspace open`

README.md
=> readme: update win install script and troubleshooting

docs/pages/cli/configuration/reference.md, docs/pages/cli/deployment/components/configuration/containers.md, docs/pages/cli/deployment/components/configuration/service.md, docs/pages/cli/deployment/components/configuration/volumes.md, docs/pages/cli/deployment/components/what-are-components.md, docs/pages/cli/deployment/helm-charts/what-are-helm-charts.md, docs/pages/cli/deployment/kubernetes-manifests/what-are-manifests.md, docs/pages/cli/development/advanced/remote-debuggers.md, docs/pages/cloud/domains/workflow.md, docs/pages/cloud/spaces/domains.md, docs/website/sidebars.json, docs/website/versioned_docs/version-v4.0.0/cli/configuration/reference.md, docs/website/versioned_docs/version-v4.0.0/cli/deployment/components/configuration/containers.md, docs/website/versioned_docs/version-v4.0.0/cli/deployment/components/configuration/service.md, docs/website/versioned_docs/version-v4.0.0/cli/deployment/components/configuration/volumes.md, docs/website/versioned_docs/version-v4.0.0/cli/deployment/components/what-are-components.md, docs/website/versioned_docs/version-v4.0.0/cli/deployment/helm-charts/what-are-helm-charts.md, docs/website/versioned_docs/version-v4.0.0/cli/deployment/kubernetes-manifests/what-are-manifests.md, docs/website/versioned_docs/version-v4.0.0/cli/development/advanced/remote-debuggers.md, docs/website/versioned_docs/version-v4.0.1/cli/deployment/components/configuration/containers.md, docs/website/versioned_docs/version-v4.0.1/cloud/domains/workflow.md, docs/website/versioned_docs/version-v4.0.1/cloud/spaces/domains.md, docs/website/versioned_docs/version-v4.0.2/cli/configuration/reference.md, docs/website/versioned_docs/version-v4.0.3/cloud/domains/workflow.md, docs/website/versioned_docs/version-v4.0.3/cloud/spaces/domains.md, docs/website/versioned_sidebars/version-v4.0.0-sidebars.json, docs/website/versioned_sidebars/version-v4.0.3-sidebars.json
=> docs: fix broken links

docs/website/sidebars.json, docs/website/versioned_sidebars/version-v4.0.0-sidebars.json, docs/website/versioned_sidebars/version-v4.0.3-sidebars.json
=> remove comma in sidebar files

docs/website/core/Footer.js, docs/website/siteConfig.js, docs/website/static/css/search.css, docs/website/static/css/star-button.css, docs/website/static/css/versions.css, docs/website/static/js/star-button.js
=> docs: add star button

docs/website/static/css/versions.css
=> improve css

docs/website/static/css/star-button.css
=> docs: improve css

docs/website/static/css/nav.css, docs/website/static/js/onpage-nav.js
=> docs: collapse onPageNav if it is too high

docs/website/static/css/versions.css
=> fix version change symbol (no unicode)

docs/website/versioned_docs/version-v4.0.1/cloud/domains/workflow.md
=> docs: fix broken link

docs/pages/cloud/clusters/connect.md
=> small correct in spelling

cmd/init.go
=> remove slash

pkg/devspace/deploy/helm/client.go
Changes:
- Fix an issue in `devspace purge` where devspace tried to delete the wrong deployment name
=> Fix issue in devspace purge

cmd/cleanup/images.go, pkg/devspace/builder/docker/docker.go, pkg/devspace/builder/kaniko/kaniko.go, pkg/devspace/cloud/registry.go, pkg/devspace/configure/image.go, pkg/devspace/docker/auth.go, pkg/devspace/docker/client.go, pkg/devspace/docker/fake.go, pkg/devspace/docker/images.go, pkg/devspace/registry/init.go
This Pull Request refactors the package in devspace/pkg/devspace/docker
- An interface ClientInterface is added containing the neccessary functions of "github.com/docker/docker/client".Client and all functions in the package that require one.
- An example Client that implements the new interface is added. Functions that used it earlier are now called with client.function(...).
- A fake implementation of the ClientInterface is added for test purposes.
=> Refactor docker client

.github/workflows/docs.yml, docs/.gitignore, docs/pages/cli/configuration/profiles-patches.md, docs/pages/introduction.md, docs/website/ci-gen-version.js, docs/website/dist/npm/etc/npmrc, docs/website/package-lock.json
Use GitHub Actions to build and deploy docs to netlify site.
No.
No.
=> docs: use github actions

.github/workflows/docs.yml, docs/pages/introduction.md
=> docs: improve ci

.github/workflows/docs.yaml, .github/workflows/release.yaml
=> rename secret to NPM_DEVSPACE_REGISTRY_TOKEN

.github/workflows/release.yaml
=> wait for release binaries to be uploaded

.github/workflows/release.yaml, dist/npm/bin/devspace, dist/npm/index.js
=> publish-npm: wait on release-ui

ui/src/components/basic/CustomDropDown/CustomDropDown.module.scss, ui/src/components/basic/CustomDropDown/CustomDropDown.tsx, ui/src/components/basic/LinkTabSelector/LinkTabSelector.module.scss, ui/src/components/basic/PageLayout/Header/Breadcrumb/Breadcrumb.tsx, ui/src/components/views/Logs/ChangeNamespace/ChangeKubeContext.module.scss, ui/src/styles/constants.scss
=> ui: minor style improvements

dist/npm/bin/devspace
=> npm: do not run execuable if it is a link (fixes npm install on mac)

.github/workflows/release.yaml
=> ci: ui: fix path for NPM_CONFIG_GLOBALCONFIG

.github/workflows/docs.yaml, docs/website/ci-gen-version.js
=> ci: update docs workflow

dist/npm/index.js, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/helm/client.go, pkg/util/analytics/analytics.go
/kind bug
resolves #797 
resolves #789 
improves send-deferred-request
=> minor fixes and improvements

README.md
=> readme: remove badge

cmd/build.go, cmd/deploy.go, cmd/dev.go, cmd/purge.go, cmd/update/dependencies.go, pkg/devspace/dependency/dependency.go, pkg/devspace/dependency/dependency_test.go, pkg/devspace/dependency/graph.go, pkg/devspace/dependency/graph_test.go, pkg/devspace/dependency/resolver.go, pkg/devspace/dependency/resolver_test.go
=> Refactor dependency pkg

cmd/add/provider.go, cmd/connect/cluster.go, cmd/create/space.go, cmd/list/clusters.go, cmd/list/spaces.go, cmd/login.go, cmd/open.go, cmd/remove/cluster.go, cmd/remove/context.go, cmd/remove/space.go, cmd/reset/key.go, cmd/use/provider.go, cmd/use/space.go, pkg/devspace/cloud/configure.go, pkg/devspace/cloud/login.go, pkg/devspace/cloud/login_test.go, pkg/devspace/cloud/resume.go, pkg/devspace/configure/image.go
Changes:
- Refactors the cloud.GetProvider method
=> Refactor provider login

docs/pages/cli/deployment/helm-charts/configuration/overview-specification.md
The "repo" option was spelled "repository"
resolves #
=> fix typo in yaml example

.gitignore, cmd/sync.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/deployer/kubectl/kubectl.go, pkg/devspace/services/client.go, pkg/devspace/services/sync.go, pkg/devspace/sync/sync.go, pkg/devspace/sync/sync_test.go, pkg/devspace/sync/tar.go, sync/server/downstream.go, sync/server/downstream_test.go, sync/server/tar.go, sync/server/upstream.go, sync/server/upstream_test.go, sync/stub/go.sum, sync/stub/main.go, sync/stub/vendor/github.com/devspace-cloud/devspace/sync/server/downstream.go, sync/stub/vendor/github.com/devspace-cloud/devspace/sync/server/tar.go, sync/stub/vendor/github.com/devspace-cloud/devspace/sync/server/upstream.go
- Fix issue where remote manifests could not be deployed (#864)
- Implement `sync.*.onDownload` & `sync.*.onUpload` (#849)
- Add `devspace sync` `--config` flag that gets the sync configuration from file (#863)
=> Sync Changes & Bug Fix

cmd/add/deployment.go, cmd/add/image.go, cmd/add/port.go, cmd/add/sync.go, cmd/init.go, cmd/remove/deployment.go, cmd/remove/image.go, cmd/remove/port.go, cmd/remove/sync.go, pkg/devspace/configure/deployment.go, pkg/devspace/configure/deployment_test.go, pkg/devspace/configure/image.go, pkg/devspace/configure/image_test.go, pkg/devspace/configure/manager.go, pkg/devspace/configure/port.go, pkg/devspace/configure/sync.go, pkg/util/factory/factory.go
The configure-package is refactored so packages that use it can fake it. Some code cleanups are done, too.
=> Refactor configure-package

cmd/dev.go, cmd/open.go, cmd/sync.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/dependency/resolver.go, pkg/devspace/services/client.go, pkg/devspace/services/port_forwarding.go, pkg/devspace/services/sync.go, pkg/devspace/sync/sync.go, pkg/devspace/sync/upstream.go, sync/stub/main.go
- Fix issue where variables in dependencies where not correctly resolved (#873)
- Add `--upload-only` and `download-only` flags to `devspace sync` (#871)
=> Bidirectional sync options & fix

cmd/print.go, cmd/root.go, cmd/ui.go, pkg/devspace/config/loader/get.go, pkg/devspace/config/loader/parse.go, pkg/devspace/config/loader/testing/fake.go
/kind feature
- new print command implemented: prints the configuration for the current or given profile after all patching and variable substitution was done.
- devspace ui -> display the right variables
=> New print command

dist/npm/index.js
=> fix npm installer when using Powershell (#911)

examples/quickstart/devspace.yaml, pkg/devspace/build/builder/docker/docker.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/docker/cli.go, pkg/devspace/docker/client.go, pkg/devspace/docker/fake.go, pkg/devspace/services/sync.go, pkg/devspace/sync/sync.go, sync/stub/main.go
Changes:
- Add images.*.build.docker.args to specify custom cli flags (#884)
- Improve cannot sync root path error message (#915)
=> Docker cli

pkg/devspace/config/loader/parse.go, pkg/devspace/config/loader/parse_test.go
Changes:
- Allows patching of the variables section (#904)
=> Allow patch var

pkg/devspace/configure/image.go
Changes:
- init: add question to skip image push (#907)
=> init: add question to skip image push (#907)

cmd/status/sync.go, cmd/status/sync_test.go, pkg/util/factory/testing/factory.go
/kind bug
resolves #921 
"devspace status sync" works now
no
=> Fix command "devspace status sync"

docs/pages/cli/configuration/profiles-patches.md, docs/pages/cli/configuration/variables.md, docs/pages/cli/deployment/advanced/dependencies.md, docs/website/versioned_docs/version-v4.0.0/cli/configuration/profiles-patches.md, docs/website/versioned_docs/version-v4.0.0/cli/configuration/variables.md, docs/website/versioned_docs/version-v4.0.0/cli/deployment/advanced/dependencies.md, docs/website/versioned_docs/version-v4.0.2/cli/configuration/variables.md, docs/website/versioned_docs/version-v4.1.0/cli/configuration/profiles-patches.md, docs/website/versioned_docs/version-v4.1.0/cli/configuration/variables.md, docs/website/versioned_docs/version-v4.2.0/cli/configuration/profiles-patches.md
=> docs: several fixes

pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/deployer/helm/client.go, pkg/devspace/deploy/deployer/helm/client_test.go
- Updates component helm chart to v0.1.3 (resolves #913, resolves #912, resolves #900) 
- Switches helm repository from charts.devspace.cloud to charts.devspace.sh (resolves #889)
No.
No.
=> update component chart repository and version

pkg/devspace/deploy/deployer/helm/deploy.go
Changes:
- Fixes an issue in `devspace render`, where 2 helm templates where not rendered correctly
=> Fix missing newline render issue #943

e2e/tests/render/expectedoutput/helm_v2, e2e/tests/render/expectedoutput/helm_v3, e2e/tests/render/helm_v2.go, e2e/tests/render/helm_v3.go, pkg/devspace/deploy/deployer/helm/deploy.go
Changes:
- Improve `devspace render` and add newline at the beginning for helm template
=> helm render: add newline

cmd/build.go, cmd/deploy.go, cmd/dev.go, cmd/list/commands.go, cmd/print.go, cmd/purge.go, cmd/remove/deployment.go, cmd/remove/space.go, cmd/render.go, cmd/reset/vars.go, cmd/run.go, cmd/set/var.go, cmd/ui.go, cmd/use/profile.go, pkg/devspace/config/loader/get.go, pkg/devspace/config/loader/parse.go, pkg/devspace/config/loader/parse_test.go, pkg/devspace/config/loader/predefined_vars.go, pkg/devspace/config/loader/testing/fake.go, pkg/devspace/dependency/dependency.go, pkg/devspace/dependency/dependency_test.go, pkg/devspace/dependency/resolver.go, pkg/devspace/dependency/resolver_test.go, pkg/devspace/server/server.go
Changes:
- Fixes an issue where dependencies were deployed in reverse order (#946)
- Fixes an issue where DEVSPACE_GIT_COMMIT was not correctly loaded in a dependency (#947)
- Refactor config loading
=> Fix dependency issue

docs/pages/cli/deployment/helm-charts/configuration/overview-specification.md
I believe that this was just a typo.
resolves #
none
no
no
simple doc typo
=> correct "repository" to be "repo"

docs/docusaurus.config.js
=> docs-new: fix logo link

docs/docusaurus.config.js
=> docs: fix logo link

docs/src/css/custom.css
=> docs: disable search

pkg/devspace/config/loader/get_test.go, pkg/devspace/config/loader/parse.go, pkg/devspace/config/loader/parse_test.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/versions.go
- Adds a new property `profiles.*.parent` that allows users to specify a parent profile that is applied before the actual profile is applied (#862)
=> Implement profile inheritance (#862)

pkg/devspace/configure/image.go
=> init: improve image repo question

.github/workflows/docs.yaml
=> docs: improve ci for versioned docs

pkg/devspace/build/builder/kaniko/kaniko.go
- Increases the waiting limit for kaniko & improves an error message
=> Increase wait limits for kaniko

docs/pages/guides/ci-cd-integration.mdx, docs/versioned_docs/version-4.6/guides/ci-cd-integration.mdx
=> docs: remove snippet for encryption key

docs/pages/configuration/development/file-synchronization.mdx, docs/versioned_docs/version-4.5/configuration/development/file-synchronization.mdx, docs/versioned_docs/version-4.6/configuration/development/file-synchronization.mdx
**What is this pull request for? Which issues does it resolve?**
Documents supported workaround for #1004
=> docs: added disableUpload and disableDownload to dev sync docs

pkg/devspace/helm/v3/client.go
Makes sure helm client does not use respositories.yaml in helm config dir which could lead to a deployment error when the temp folder is corrupted or missing.
No
No
=> helm(v3): make chart deploy more resilient

docs/docusaurus.config.js, docs/package.json, docs/yarn.lock
Upgrade docusaurus and add `target: _self` to website links/
=> docs: upgrade dependencies

pkg/devspace/build/builder/custom/custom.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/v1beta7/upgrade.go, pkg/devspace/config/versions/v1beta7/upgrade_test.go
- rename imageArg -> imageFlag
=> imageArg -> imageFlag

pkg/devspace/services/sync.go
/kind bug
fixes sync on windows
=> fix: sync on windows

pkg/devspace/deploy/deployer/kubectl/builder.go
- fixes a small issue in the prepare resources method of the kubectl deployer
=> fix issue in kubectl prepare resources

docs/versioned_docs/version-4.7/guides/localhost-ui.mdx
**What is this pull request for? Which issues does it resolve?**
Fixes type in the devspace ui docs
**Does this pull request has user-facing changes?** 
No
No
Nothing :)
=> Fix typo in devspace ui command

.github/workflows/release.yaml
=> ci: do not run windows tests on master (for now)

dist/npm/bin/devspace, dist/npm/bin/devspace.cmd, dist/npm/index.js
Allows running DevSpace via npx and improves handling with npm and yarn.
=> install: make npx work and improve installer for npm and yarn

examples/hot-reload-container-restart/devspace.yaml, pkg/devspace/build/builder/restart/restart.go
- Improve hot reload comments
- Fix small typo in restart script
=> improve hot reload example

docs/pages/getting-started/initialize-project.mdx
quick start for java https://github.com/devspace-cloud/quickstart-java
/kind bug
/kind feature
resolves #
=> Add quick start for java

pkg/devspace/sync/initial.go, pkg/devspace/sync/sync.go, pkg/devspace/sync/sync_test.go, pkg/devspace/sync/upstream.go
- fixed an issue where uploadExcludePaths and downloadExcludePaths were not correctly applied during initial sync
=> fix upstream/downstream exclude initial sync problem

.github/workflows/npm.yaml, .github/workflows/release.yaml, .github/workflows/ui.yaml, dist/npm/bin/devspace, dist/npm/bin/devspace.cmd, dist/npm/index.js
/kind bug
- fixes npm installer for linux/mac
- adds CI tests for npm installer
=> Fix npm install

.github/workflows/release.yaml, .github/workflows/ui.yaml
=> ci: set CI=false for UI build

docs/pages/getting-started/initialize-project.mdx, docs/pages/guides/ci-cd-integration.mdx, docs/versioned_docs/version-4.11/getting-started/initialize-project.mdx, docs/versioned_docs/version-4.11/guides/ci-cd-integration.mdx
=> docs: add dotnet quickstart

docs/pages/getting-started/initialize-project.mdx, docs/versioned_docs/version-4.11/getting-started/initialize-project.mdx
=> docs: fix typo

cmd/init.go
=> init: add .git/ to excludePaths

cmd/connect/cluster.go
- disables gatekeeper by default during cluster connect
=> disable gatekeeper by default

dist/npm/bin/devspace, dist/npm/bin/devspace.cmd, dist/npm/index.js, dist/npm/package.json
=> install: fix npm install in powershell #911

dist/npm/bin/devspace.cmd
/kind bug
resolves #911 (fixes issues with spaces in path to global npm folder)
=> install: fix issue with spaces in npm path #911

Dockerfile
/kind feature
**What is this pull request for? Which issues does it resolve?** 
update to alpine 3.11.6 to fix several security issues.
Pulls new base image
Requires new base image 
=> dockerfile: update to alpine 3.11.6

pkg/devspace/kubectl/client.go, pkg/devspace/kubectl/exec.go, pkg/devspace/kubectl/testing/client.go, pkg/devspace/server/enter.go, pkg/devspace/services/attach.go, pkg/devspace/services/sync.go, pkg/devspace/services/terminal.go
- Fixes an issue where the terminal button in the localhost UI was not working correctly
=> Fix UI terminal not opening

docs/pages/guides/community-projects.mdx, docs/versioned_docs/version-4.12/guides/community-projects.mdx
Adds [Addono/trilium-devspace](https://github.com/Addono/trilium-devspace) to the list of community projects.
=> docs(community projects): Add Addono/trilium-devspace

pkg/devspace/build/builder/kaniko/kaniko.go
- Fixes a nil pointer in the pod status check during kaniko build (#1097)
=> Fix kaniko nil pointer #1097

dist/npm/bin/devspace.cmd, dist/npm/index.js, dist/npm/package.json
Makes sure npm installer works correctly on windows
=> npm: enabledelayedexpansion vars in cmd script

pkg/devspace/deploy/deployer/helm/client.go
Bump component chart version to v0.2.0 (fixes #1088)
=> component-chart: use v0.2.0

pkg/devspace/deploy/deployer/helm/client.go
updates component chart to v0.3.0
=> component-chart: v0.3.0

dist/npm/bin/devspace.cmd, dist/npm/index.js, dist/npm/package-lock.json, dist/npm/package.json
/kind bug
improves installer logic
=> npm: improve installer

dist/npm/bin/devspace
=> installer: npx compatibility

.github/workflows/npm.yaml, dist/npm/bin/devspace, dist/npm/bin/devspace.cmd, dist/npm/index.js
Changes required to allow using devspace via npx
=> ci: add npx test + improvements for npx

dist/npm/bin/devspace, dist/npm/bin/devspace.cmd, dist/npm/index.js
=> npm: remove unnecessary output

dist/npm/bin/devspace, dist/npm/index.js
=> npm: small improvements for local installs and shell compatibility

dist/npm/bin/devspace
=> Fix devspace install from npm on macos

.gitignore, cmd/deploy.go, cmd/dev.go, cmd/ui.go, examples/kaniko/devspace.yaml, pkg/devspace/build/builder/kaniko/build_pod.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/dependency/dependency.go, pkg/devspace/kubectl/client.go, pkg/devspace/kubectl/testing/client.go, pkg/devspace/kubectl/util.go, pkg/devspace/server/server.go, ui/package-lock.json, ui/public/index.html, ui/src/components/advanced/InteractiveTerminal/InteractiveTerminal.tsx, ui/src/components/views/Logs/Pod/Pod.tsx, ui/src/contexts/withDevSpaceConfig/DevSpaceConfigWrapper.tsx, ui/src/lib/fetch.ts, ui/src/pages/logs/containers.tsx
- Fixes a security vulnerability in the devspace ui server (#1128)
- Automatically creates deployment namespaces if they do not exist before deploying (#1127)
- Adds support for specifying the kaniko pod resources in the devspace.yaml (#1126)
=> Various Improvements

ui/src/components/views/Logs/LogsList/LogsList.module.scss, ui/src/components/views/Logs/LogsList/LogsList.tsx
=> feat(ui): add search bar for pods

pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/deployer/helm/client.go
=> feat: add startupProbe for component-chart (#1157)

cmd/root.go, pkg/devspace/plugin/plugin.go
- Fixes an issue where on several occasions devspace log output was printed to plugin commands
=> fix: fixes an issue where log output was printed to plugin commands

cmd/deploy.go, cmd/dev.go, cmd/root.go, cmd/sync.go, go.mod, go.sum, pkg/devspace/upgrade/upgrade.go
- Fixes an issue where upgrade message could be displayed where they shouldn't
- Disable klog messages for the devspace command (#1179)
=> fix: fixes an issue with upgrade messages & klog messages

docs/versioned_docs/version-5.0/configuration/variables/basics.mdx
resolves #
Only documentation sample
=> fix: Error in sample of using custom tags

pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/deployer/helm/client.go, pkg/devspace/tunnel/client.go
- Fixes an issue where larger files couldn't be forwarded correctly in remote port forwarding
- Updates the component chart to v0.6.0 and adds new options to the schema
=> fix: fixes an issue with large files in remote port forwarding

pkg/devspace/kubectl/exec.go, pkg/devspace/server/enter.go, pkg/devspace/server/server.go, ui/public/index.html, ui/src/components/advanced/InteractiveTerminal/InteractiveTerminal.tsx, ui/src/components/views/Logs/TerminalCache/TerminalCache.tsx, ui/src/lib/fetch.ts
- Fixes an issue where the terminal didn't have the correct size (#1190)
=> fix(ui): resize terminal correctly in the backend

pkg/devspace/server/server.go
- Fixes an issue where `devspace ui` would return an 404 error
=> fix(ui): fxies an issue where the ui would display 404

docs/versioned_docs/version-5.0/configuration/dependencies/git-repository.mdx
DevSpace does not pull latest commits automatically anymore. It requires a separate command.
Inaccurate documentation
No
=> Updated caching explanation

docs/pages/configuration/deployments/helm-charts.mdx, docs/pages/fragments/profile-parent.mdx, pkg/devspace/deploy/deployer/helm/client.go, pkg/devspace/kubectl/logs.go, pkg/devspace/kubectl/util/util.go, pkg/devspace/services/targetselector/target_selector.go
- Fixes an issue where in certain circumstances a nil pointer panic could occur when devspace tries to ask a question
- Updates the component-chart and adds several new config options to initContainers #1207
- If no config could be loaded falls back to the in cluster config #1205
- Stream logs from all containers in a pod #1211
=> fix: fixes a nil pointer if the pod or container question is not set

docs/versioned_docs/version-5.2/configuration/profiles/patches.mdx
Documentation edit. In memory profile config did not reflect the correct changes that were applied by the profile patch.
**Does this pull request has user-facing changes?** (e.g. config changes, new/modified commands, new/modified flags)
=> Fix patches.mdx

pkg/devspace/config/loader/get.go, pkg/devspace/config/loader/get_test.go, pkg/devspace/dependency/resolver.go
=> fix: dependency local paths are relative to config

docs/pages/configuration/variables/source-command.mdx, docs/sidebars.js, pkg/devspace/config/loader/parse.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/hook/hook.go, pkg/util/command/command.go
- Adds `source: command` to vars
=> add env source command

docs/versioned_docs/version-5.4/guides/file-synchronization.mdx
typofix, no issue
no
no
doc typofix
=> [docs/guides/file-syncronisation] typo fix

cmd/build.go, pkg/devspace/build/builder/kaniko/kaniko.go
- `devspace build` now works correctly when provided a namespace via `--namespace`
- improve error detection if the kaniko build pod cannot start up
=> improvement: improve kaniko error detection & fix devspace build namespace issue

examples/custom-builder/custom/build, examples/custom-builder/custom/build.cmd, pkg/devspace/build/builder/custom/custom.go
- Fixes an issue where DevSpace would not correctly pass the tags to the custom builder
=> fix: fixes an issue for custom builds

pkg/devspace/services/port_forwarding.go, pkg/devspace/services/reverse_port_forwarding.go
- Fixes an issue where port-forwarding wouldn't work anymore after auto-reload when `imageName` was specified
=> fix: port-forwarding in auto reload

.github/workflows/release.yaml, go.mod, go.sum, hack/build-all.bash, pkg/devspace/build/build.go, pkg/devspace/build/builder/kaniko/kaniko.go, pkg/devspace/build/testing/fake.go, pkg/devspace/config/loader/predefined_vars.go, pkg/devspace/sync/util_test.go, pkg/util/randutil/rand.go, pkg/util/randutil/rand_test.go, vendor/github.com/rjeczalik/notify/event_fen.go, vendor/github.com/rjeczalik/notify/event_fsevents.go, vendor/github.com/rjeczalik/notify/event_kqueue.go, vendor/github.com/rjeczalik/notify/event_stub.go, vendor/github.com/rjeczalik/notify/event_trigger.go, vendor/github.com/rjeczalik/notify/notify.go, vendor/github.com/rjeczalik/notify/watcher_fen.go, vendor/github.com/rjeczalik/notify/watcher_fen_cgo.go, vendor/github.com/rjeczalik/notify/watcher_fsevents.go, vendor/github.com/rjeczalik/notify/watcher_fsevents_cgo.go, vendor/github.com/rjeczalik/notify/watcher_inotify.go, vendor/github.com/rjeczalik/notify/watcher_kqueue.go, vendor/github.com/rjeczalik/notify/watcher_notimplemented.go, vendor/github.com/rjeczalik/notify/watcher_readdcw.go, vendor/github.com/rjeczalik/notify/watcher_trigger.go, vendor/modules.txt
- Update notify dependency
- Update go version to 1.15
- Build darwin version without CGO
=> Dependency Updates

pkg/devspace/deploy/deployer/helm/client.go
- Update component chart to v0.7.1
=> chore: update component chart to v0.7.1

cmd/init.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/configure/deployment.go, pkg/devspace/configure/image.go, pkg/devspace/kubectl/client.go
=> chore: improve init command

dist/npm/index.js
=> fix(npm): fixes #1251

pkg/devspace/config/loader/get.go, pkg/devspace/config/loader/parse.go, pkg/devspace/config/loader/validate.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/versions.go, pkg/devspace/services/reverse_port_forwarding.go, pkg/devspace/tunnel/client.go
- Improves config validation for profiles, sync and port forwarding
=> refactor: improve config validation

pkg/devspace/build/builder/kaniko/kaniko.go
- prevent pull secret creation if disabled for kaniko
=> improvement: prevent pull secret creation if disabled for kaniko

dist/npm/index.js
=> fix: npm install

.github/workflows/release.yaml, hack/build-all.bash, pkg/devspace/kubectl/util.go
- Finding pods by imageName now allows to find images that have no tag if the specified `devspace.yaml` config tag is latest
- Add support for darwin arm64 builds
=> improvement: allow image:latest == image

cmd/dev.go
/kind feature
it adds a new flag
yes, the user can now use a new flag when running devspace dev
no
=> feat: add flag ui-port

.github/workflows/release.yaml, cmd/dev.go, pkg/devspace/server/server.go
- Log ui errors to file
- Fixed an issue where an UI error could lead to a nil pointer panic
- Use Golang Version 1.16 for building
=> improvement: log ui errors to log file

pkg/devspace/config/loader/parse.go
- DevSpace will now print the config var commands stderr and stdout on failure
=> improvement: show stdout & stderr on var command failure

docs/versioned_docs/version-5.9/getting-started/development.mdx
=> docs: correct the section number

cmd/set/var.go
/kind bug
Base64 encoded strings often end with `=` and that leads to a problem with this if condition being true and resulting in a fatal.
=> fix: allow setting base64 encoded variable values

dist/npm/bin/devspace
=> fix(npm): fixes issue #1363

cmd/list/vars.go
Sort by var name in output table for command `devspace list vars`
=> fix: sort vars in output table of list vars

pkg/devspace/services/log_manager.go
- DevSpace will now use the deployment, statefulset or replicaset name instead of the pod name for the log streaming prefix if no `app.kubernetes.io/component` label is found
=> refactor: use deployment name for log tag if found

cmd/list/deployments.go, pkg/devspace/config/config.go, pkg/devspace/config/generated/config.go, pkg/devspace/config/loader/variable/predefined_variable.go, pkg/devspace/dependency/dependency.go, pkg/devspace/dependency/types/types.go, pkg/devspace/deploy/deploy.go, pkg/devspace/deploy/deploy_test.go, pkg/devspace/deploy/deployer/helm/client.go, pkg/devspace/deploy/deployer/helm/client_test.go, pkg/devspace/deploy/deployer/helm/deploy.go, pkg/devspace/deploy/deployer/helm/deploy_test.go, pkg/devspace/deploy/deployer/helm/render.go, pkg/devspace/deploy/deployer/helm/status.go, pkg/devspace/deploy/deployer/interface.go, pkg/devspace/deploy/deployer/kubectl/kubectl.go, pkg/devspace/deploy/deployer/kubectl/kubectl_test.go, pkg/devspace/deploy/deployer/util/replace.go, pkg/devspace/deploy/deployer/util/replace_test.go, pkg/util/imageselector/imageselector.go
- New replacement functions `imageName()`, `imageNameImage()` and `imageNameTag()` to easily reference images from dependencies:
```yaml
dependencies:
- name: dep1
source:
path: dep1
deployments:
- name: quickstart
helm:
componentChart: true
values:
containers:
- image: imageName(dep1.default)
```
=> feat: add imageName(), imageNameImage() and imageNameTag()

pkg/devspace/kubectl/util.go
- Ignore forbidden error during initial namespace check (fix #1401)
=> improvement: do not require namespace get permissions

docs/pages/fragments/start-app.mdx, docs/pages/quickstart.mdx, docs/versioned_docs/version-5.12/fragments/start-app.mdx, docs/versioned_docs/version-5.12/quickstart.mdx
resolves #
It addresses three things in the Quickstart doc:
1. Update the path for starting the example Java app.
2. Add instruction to use the existing Dockerfile for quickstart projects.
3. Add instruction to exit the container after testing developerment.
Docs changes only.
No.
=> update quickstart docs

cmd/open.go, pkg/devspace/config/config.go
- Fixes an issue where port forwarding with `devspace open` would not work correctly
=> fix: fix devspace open

pkg/devspace/services/sync.go, pkg/devspace/services/synccontroller/controller.go, pkg/util/log/file_logger.go, pkg/util/log/prefix_logger.go
- Sync will now be started concurrently (up to 5 sync configurations at a time)
- Sync file messages will now indicate from which sync configuration the message originated
=> improvement: start sync concurrently & improve logging

helper/cmd/sync/upstream.go, helper/server/tar.go, helper/server/upstream.go, pkg/devspace/services/synccontroller/controller.go, pkg/devspace/sync/evaluater.go, pkg/devspace/sync/file_information.go, pkg/devspace/sync/initial.go, pkg/devspace/sync/tar.go, pkg/devspace/sync/upstream.go
- devspace will now override file permissions remotely on linux and darwin operating systems
=> improvement(sync): override permissions on file sync on darwin & linux

pkg/devspace/config/loader/validate.go
/kind bug
No issue created
no
no
When using multiple entries inside of `dev.replacePods`, this function would fail incorrectly because the comparison was being done on the wrong fields.
=> Compare ImageName on replacePods

docs/pages/fragments/kube-context.mdx, docs/pages/guides/plugins.mdx
Fixes a broken link.
Explains what Loft is (_chapter 3. - Kube-context & Namespace - Remote Cluster - Share cluster with others_).
No?
No
-
=> Docs improvements

pkg/devspace/config/loader/validate.go
Added empty string checks for validation of image selector and image label .
/kind bug
resolves #1499 
No 
The fix is to update the empty string check
=> Update validation logic in replace pods unique

docs/pages/configuration/deployments/helm-charts.mdx, docs/pages/configuration/reference.mdx
Contributed this change https://github.com/loft-sh/devspace/pull/1423 few months ago but never got to write the documentation for it.
Here it is.
=> Add helm displayOutput documentation

docs/pages/configuration/variables/basics.mdx, docs/pages/configuration/variables/source-input.mdx, docs/pages/fragments/config-vars.mdx, pkg/devspace/config/loader/variable/default_variable.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/v1beta9/schema.go
/kind feature
https://github.com/loft-sh/devspace/issues/1331
resolves #1331 
Add new option to disable cache on variables
Add new option that defaults to false. Backward compatible
No
No exactly sure what's the strategy with the schema versions. I added to latest and v9 but let me know if you want it done a different way, or if you want a new version.
=> add noCache field to variables

pkg/devspace/deploy/deployer/helm/client.go, pkg/devspace/kubectl/selector.go
- Updated component chart to v0.8.1
- Fixed an issue where the image selector would sometimes look wrong
=> Image Selector Fix & Component Chart Bump

helper/cmd/root.go
- Renamed devspace-restart-helper -> devspacehelper
=> fix: rename devspace-restart-helper -> devspacehelper

pkg/devspace/sync/initial.go, pkg/devspace/sync/sync.go
- Fixed an issue where devspace would not correctly upload files initially
=> fix: fixes an issue where initial sync would not upload files correctly

pkg/devspace/sync/upstream.go
- Improved sync logging to omit duplicate files
=> refactor: improve sync logging

e2e/new/README.md, e2e/new/framework/util.go, e2e/new/tests/build/build.go, e2e/new/tests/command/command.go, e2e/new/tests/command/framework.go, e2e/new/tests/dependencies/dependencies.go, e2e/new/tests/portforward/framework.go, e2e/new/tests/portforward/portforward.go, e2e/new/tests/pullsecret/framework.go, e2e/new/tests/pullsecret/pullsecrets.go
- Adds todos for the e2e tests
=> test: add e2e test todos

cmd/deploy.go, cmd/sync.go
- Fixed an issue where `devspace sync --config ...` would use the current directory as base path instead of the config directory
=> fix: fixed an issue where devspace sync had the wrong base path

cmd/dev.go
- `--dependency` will not execute whole pipeline in `devspace dev`
=> fix: --dependency will not execute whole pipeline in devspace dev

pkg/devspace/plugin/plugin.go
- Fixed an issue where using relative paths for plugin installation would fail
=> fix: fixed an issue where plugin paths were not correctly resolved

cmd/sync.go, e2e/new/framework/helper.go, e2e/new/kube/kube.go, e2e/new/tests/dependencies/dependencies.go, e2e/new/tests/deploy/deploy.go, e2e/new/tests/sync/sync.go, e2e/new/tests/sync/testdata/sync-containers/devspace.yaml, e2e/new/tests/sync/testdata/sync-containers/file1.txt, e2e/new/tests/sync/testdata/sync-simple/file1.txt, e2e/new/tests/sync/testdata/sync-simple/no-watch.yaml, e2e/new/tests/sync/testdata/sync-simple/watch.yaml, pkg/devspace/services/client.go, pkg/devspace/services/sync.go
- Fix an issue where `devspace sync` would exit immediately after initial sync and hooks
=> fix: devspace sync --config devspace.yaml does not watch

pkg/devspace/generator/language.go
- Fixed an issue where updating the local init language repository could fail during `devspace init`
=> fix: delete language git repo if there is an error on update

docs/pages/guides/plugins.mdx, docs/versioned_docs/version-5.15/guides/plugins.mdx, pkg/devspace/plugin/hook.go
- Added a new environment variable DEVSPACE_PLUGIN_SESSION
=> feat: add DEVSPACE_PLUGIN_SESSION

e2e/new/tests/build/build.go, e2e/new/tests/build/testdata/docker/Dockerfile, e2e/new/tests/build/testdata/docker/devspace.yaml, pkg/devspace/docker/client.go
**This PR adds/updates:**
- "should build dockerfile with docker" e2e test in e2e/new/tests/build.go file.
- New DockerApiClient() to Client interface in docker package.
Signed-off-by: pratikjagrut <26519653+pratikjagrut@users.noreply.github.com>
No
No
=> Add build e2e test.

e2e/new/tests/build/build.go, e2e/new/tests/build/testdata/buildkit/Dockerfile, e2e/new/tests/build/testdata/buildkit/devspace.yaml
This PR adds/updates:
- "should build dockerfile with buildkit" e2e test in e2e/new/tests/build.go file.
Signed-off-by: pratikjagrut 26519653+pratikjagrut@users.noreply.github.com
What issue type does this pull request address? (keep at least one, remove the others)
Does this pull request has user-facing changes? (e.g. config changes, new/modified commands, new/modified flags)
No
Does this pull request add new dependencies?
No
=> [Build e2e] Add "should build dockerfile with buildkit" test

pkg/devspace/deploy/deployer/util/replace.go, pkg/devspace/kubectl/selector/selector.go, pkg/devspace/services/podreplace/podreplace.go, pkg/util/imageselector/imageselector.go
- Fixed an issue where replacing pods with the same image selector across `devspace.yaml` would target the same pods
=> fix: fixed issue with same image selector in shared namespace

e2e/new/e2e_suite_test.go, e2e/new/tests/init/framework.go, e2e/new/tests/init/init.go, pkg/devspace/configure/image.go
=> feat: add skip registry option to init

.github/workflows/pr-checks.yml, .github/workflows/release.yaml, cmd/dev.go, cmd/root.go, pkg/devspace/config/loader/loader_test.go, pkg/devspace/services/terminal.go, pkg/util/interrupt/interrupt.go
It moves unit test jobs to pr-checks workflow
No
No
=> ci: move unit test jobs to pr-checks workflow

examples/kind/.dockerignore, examples/kind/.gitignore, examples/kind/Dockerfile, examples/kind/README.md, examples/kind/devspace.yaml, examples/kind/index.js, examples/kind/kind-with-registry-non-secure.sh, examples/kind/package-lock.json, examples/kind/package.json
Adds an example to use devspace with kind resgistry.
=> doc: add kind exmaple

pkg/devspace/services/port_forwarding.go, pkg/devspace/services/reverse_port_forwarding.go
- Improved port forwarding & reverse port forwarding logging
=> refactor: improve port forwarding & reverse port forwarding logging

pkg/util/shell/cat.go, pkg/util/shell/cat_test.go, pkg/util/shell/shell.go, pkg/util/shell/shell_test.go
/kind feature
This PR adds support for cat command for windows users.
Yes
No
=> feat: add cat command

docs/pages/fragments/dependency-dev.mdx, e2e/tests/dependencies/dependencies.go, e2e/tests/dependencies/testdata/dev-replacepods/dep.yaml, e2e/tests/dependencies/testdata/dev-replacepods/devspace.yaml
resolves #
This PR adds e2e test.
NO
NO
=> e2e: add test for the new option dependencies[*].dev.replacePods

helper/tunnel/server.go, pkg/devspace/kubectl/portforward/portforward.go
- Fixed an issue where the port-forwarder would restart too often
- Fixed an issue where the reverse port forwarder would sometimes not restart correctly
=> Fix port forwarding & reverse port forwarding

pkg/devspace/config/loader/loader_test.go, pkg/devspace/config/loader/validate.go, pkg/devspace/config/loader/validate_test.go
/kind feature
resolves #
This PR adds validation for images name to avoid issues like #1690.
No
No
=> feat: validate image name

pkg/devspace/kubectl/client.go, pkg/devspace/kubectl/client_test.go
/kind feature
**What is this pull request for? Which issues does it resolve?**
This PR updates the default k8s user agent
No
No
=> feat: change default kubernetes user agent to DevSpace Version vX.X.X

pkg/devspace/config/loader/validate.go, pkg/devspace/config/loader/validate_test.go
/kind feature
**What is this pull request for? **
It adds more config validation 
No
No
=> feat: add more config validation

e2e/tests/build/build.go, e2e/tests/build/testdata/custom_build/Dockerfile, e2e/tests/build/testdata/custom_build/build.sh, e2e/tests/build/testdata/custom_build/devspace.yaml
**What is this pull request for? **
This PR adds an e2e test for a custom builder.
No
No
=> e2e: add custom build test

e2e/tests/build/build.go, e2e/tests/build/testdata/kaniko/Dockerfile, e2e/tests/build/testdata/kaniko/devspace.yaml
It adds e2e test for kaniko build option
No
No
=> e2e: add kaniko build test

pkg/devspace/build/builder/helper/helper.go, pkg/devspace/build/builder/helper/helper_test.go
- Improve local image lookup to consider all tags
=> fix: local image lookup does not consider all tags

cmd/root.go, go.mod, helper/server/downstream.go, helper/server/ignoreparser/ignoreparser.go, helper/server/upstream.go, pkg/devspace/kubectl/copy.go, pkg/devspace/sync/initial.go, pkg/devspace/sync/sync.go, pkg/devspace/sync/upstream.go, pkg/devspace/watch/watch.go, vendor/modules.txt
- Added a warning for problematic exclude paths
- Fixed an issue where klog v2 messages would be visible to the user
=> refactor: add warning if problematic exclude path is found

e2e/tests/build/build.go, pkg/devspace/build/builder/helper/util.go
=> fix: fix Dockerignore.dockerignore file path selection

docs/pages/configuration/images/custom.mdx
resolves #
Replaces the description of `onChange` option where the description of `command` should be with the correct description.
No
No
=> docs: fix description of custom build command

pkg/util/shell/shell.go
=> fix: select current running bin

PULL_REQUEST_TEMPLATE.md
=> refactor: add /kind test to pr template

pkg/devspace/services/synccontroller/controller.go
/kind bugfix
resolves #
#1743
No
No
=> fix: adjust sync path for mac os

pkg/devspace/services/inject/inject.go
- Display stdout / stderr if downloading devspacehelper fails
=> refactor: show stdout / stderr if download inject fails

cmd/analyze.go, cmd/deploy.go, cmd/dev.go, cmd/flags/flags.go, cmd/list/deployments.go, cmd/open.go, cmd/purge.go, cmd/reset/pods.go, cmd/restart.go, cmd/restore/vars.go, cmd/save/vars.go, cmd/sync.go, cmd/ui.go, pkg/devspace/kubectl/client.go, pkg/devspace/kubectl/client_test.go, pkg/devspace/kubectl/testing/client.go, pkg/util/log/testing/fake.go
/kind feature
resolves #
If the Kube context or the namespace is changed it prompts a question asking which context/namespace to use.
Deprecates `-s` flag
No
=> WIP: feat: ask context and namespace if changed

cmd/render.go
/kind feature
resolves #
#1768 
No
No
=> feat: use fake client in case kubeconfig is not found in render command

docs/pages/configuration/deployments/helm-charts.mdx, docs/pages/configuration/reference.mdx, e2e/tests/deploy/deploy.go, e2e/tests/deploy/testdata/helm_git/devspace.yaml, e2e/tests/deploy/testdata/helm_git_branch/devspace.yaml, e2e/tests/deploy/testdata/helm_git_subpath/devspace.yaml, pkg/devspace/config/loader/validate.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/helm/v2/install.go, pkg/devspace/helm/v3/client.go
/kind feature
/kind docs
/kind test
resolves #
Add support for installing helm chart directly from git.
Yes
No
=> feat: install helm chart directly from git

pkg/devspace/config/versions/latest/schema.go
/kind bugfix
resolves #
#1789 
Yes
No
=> fix: typo in SyncExec config

docs/pages/commands/devspace_list_deployments.md, pkg/devspace/helm/generic/generic.go, pkg/devspace/helm/v2/install.go, pkg/devspace/helm/v3/client.go
/kind feature
resolves #
#1772 
Add --max flag to devspace list deployments
No
=> feat: add --max flag to list deployments command

pkg/devspace/config/loader/expression/expression.go, pkg/devspace/config/loader/loader.go, pkg/devspace/config/loader/parser.go, pkg/devspace/config/loader/variable/resolver.go, pkg/devspace/config/loader/variable/types.go
- Refactor variable interface to allow easier variable resolving
=> refactor: make variable resolver easier to reuse

cmd/print.go, cmd/run.go, pkg/devspace/dependency/dependency.go, pkg/devspace/dependency/types/types.go
- New `--dependency` flag for `devspace print` to show a loaded dependency config
=> feat: new --dependency flag for devspace print

helper/server/downstream.go, helper/server/tar.go, helper/server/upstream.go, pkg/devspace/hook/upload.go, pkg/devspace/sync/downstream.go, pkg/devspace/sync/evaluater.go, pkg/devspace/sync/initial.go, pkg/devspace/sync/tar.go, pkg/devspace/sync/upstream.go, pkg/util/fsutil/filesystem.go
- Fixed an issue where DevSpace would hang starting the sync if a recursive symlink was found
- Improved sync change detection for folders
=> fix: fix recursive symlinks

dist/npm/bin/devspace
/kind bugfix
resolves #1185 
Fixed an issue where DevSpace does not run in Alpine when installed via npm
=> Fix Alpine / Busybox compatibility

e2e/tests/dependencies/dependencies.go, e2e/tests/dependencies/testdata/cyclic/dependency/devspace.yaml, e2e/tests/dependencies/testdata/cyclic/devspace.yaml, pkg/devspace/dependency/resolver.go
/kind bugfix
resolves #
#1818 
Fixed an issue where DevSpace was getting `Invalid memory address or nil pointer dereference` while resolving cyclic dependency. Also adding an e2e test for the same bug.
=> fix: nil cyclic dependency error

.github/ISSUE_TEMPLATE/bug-report.md
=> enhancement: add ARCH option in the bug report

pkg/devspace/helm/v2/install.go
/kind bugfix
resolves #
Removes unknown repository-config flag from helm v2.
Fixed an issue where DevSpace 5.18.0 throws an error of unknown flag with helm v2.
=> fix: remove repository-config flag for helm v2

pkg/devspace/kubectl/client.go
/kind bugfix
Fixed an issue where DevSpace would panic on `devspace sync`
=> fix: fix nil pointer in check kube context

cmd/init.go
Talked offline with @LukasGentele 
Added docs for `excludePaths` in default template.
Nice work on the tool!
=> chore: Added comment for `excludePaths` following `.gitignore` format

docs/pages/configuration/variables/source-command.mdx, docs/pages/configuration/variables/source-env.mdx, docs/pages/configuration/variables/source-input.mdx, docs/pages/configuration/variables/source-none.mdx, docs/pages/fragments/config-vars.mdx, e2e/tests/config/config.go, e2e/tests/config/testdata/runtime-variables/command.txt, e2e/tests/config/testdata/runtime-variables/devspace.yaml, e2e/tests/init/init.go, pkg/devspace/config/loader/variable/resolver.go, pkg/devspace/config/loader/variable/runtime/runtime_resolver.go, pkg/devspace/config/versions/latest/schema.go
/kind bugfix
/kind feature
resolves #1829
Fixed an issue where DevSpace would not resolve variables correctly after applying config expressions
New option `vars.*.alwaysResolve` to signal DevSpace to resolve a variable even though it is not loaded in the config directly
=> refactor: alwaysResolve & resolve after config expressions

e2e/tests/config/config.go, e2e/tests/config/testdata/profile-patches/path-variable.yaml, pkg/devspace/config/loader/loader.go, pkg/devspace/config/loader/loader_test.go
/kind bugfix
/kind test
resolves #
#1835
=> fix: remove path variable check

cmd/deploy.go, cmd/dev.go, cmd/render.go, docs/pages/commands/devspace_deploy.md, docs/pages/commands/devspace_dev.md, docs/pages/commands/devspace_render.md, docs/versioned_docs/version-4.13/commands/devspace_deploy.md, docs/versioned_docs/version-4.13/commands/devspace_dev.md, docs/versioned_docs/version-4.13/commands/devspace_render.md, docs/versioned_docs/version-5.15/commands/devspace_deploy.md, docs/versioned_docs/version-5.15/commands/devspace_dev.md, docs/versioned_docs/version-5.15/commands/devspace_render.md, docs/versioned_docs/version-5.16/commands/devspace_deploy.md, docs/versioned_docs/version-5.16/commands/devspace_dev.md, docs/versioned_docs/version-5.16/commands/devspace_render.md, docs/versioned_docs/version-5.17/commands/devspace_deploy.md, docs/versioned_docs/version-5.17/commands/devspace_dev.md, docs/versioned_docs/version-5.17/commands/devspace_render.md, docs/versioned_docs/version-5.18/commands/devspace_deploy.md, docs/versioned_docs/version-5.18/commands/devspace_dev.md, docs/versioned_docs/version-5.18/commands/devspace_render.md, vendor/github.com/nxadm/tail/tail.go
typo fix in help output documentation
=> fix typo in --help output

cmd/root.go
resolves #1841
Removed the `devspace help` command as it collides with devspace plugin commands
=> refactor: remove devspace help command

cmd/print.go, e2e/tests/dependencies/dependencies.go, e2e/tests/dependencies/testdata/overlapping/dep1/devspace.yaml, e2e/tests/dependencies/testdata/overlapping/dep2/devspace.yaml, e2e/tests/dependencies/testdata/overlapping/dep3/devspace.yaml, e2e/tests/dependencies/testdata/overlapping/devspace.yaml, pkg/devspace/dependency/dependency.go
/kind bugfix
resolves #1845
Fixed an issue where DevSpace would deploy the same dependency multiple times
`devspace print` will now also print the dependency tree
=> Deduplicate dependencies & print dependency tree

cmd/dev.go, docs/pages/configuration/development/terminal.mdx, e2e/tests/terminal/terminal.go, e2e/tests/terminal/testdata/run_cmd_locally/devspace.yaml
=> Run cmd locally if no imageSelector and labelSelector is provided in dev.terminal

cmd/run.go
=> fix: fix for #1857

pkg/devspace/config/versions/latest/schema.go
=> fix: add Shared field in VolumeMountVolumeConfig

cmd/run.go
=> fix: completion test log issue

cmd/build.go
/kind feature
resolves #
#1852
=> feat: better log msg if no image is defined in config file.

CONTRIBUTING.md
=> enhancement: update contribution guide

.vscode/launch.json
/kind test
adds vscode config for e2e
Just splitting that off from the concurrent deploy PR.
This mimics what vcluster has and allows to easily debug e2e.
=> add vscode config for e2e

cmd/init.go
- Standardize image question for helm, kubectl and kustomizations deployments
=> refactor: standardize image question across helm, kubectl, and kustomize

docs/versioned_docs/version-5.18/configuration/development/auto-reloading.mdx
This pull request just fix a tiny typo in the docs.
Fixed a typo in devspace docs about auto-reloading
=> docs: fix typo in auto-reloading docs

pkg/devspace/services/targetselector/until_newest_running.go
- Reorders the DevSpace warnings while waiting
=> refactor: reorder DevSpace warnings

helper/server/downstream_test.go, helper/server/upstream_test.go, pkg/devspace/build/builder/helper/util_test.go, pkg/devspace/config/generated/config_test.go, pkg/devspace/config/loader/loader_test.go, pkg/devspace/dependency/dependency_test.go, pkg/devspace/dependency/resolver_test.go, pkg/devspace/docker/auth_test.go, pkg/devspace/docker/config_test.go, pkg/devspace/generator/language_test.go, pkg/devspace/sync/sync_test.go, pkg/devspace/upgrade/upgrade_test.go, pkg/devspace/watch/watch_test.go, pkg/util/dockerfile/get_test.go, pkg/util/fsutil/filesystem_test.go, pkg/util/git/git_test.go, pkg/util/hash/hash_test.go, pkg/util/kubeconfig/kubeconfig_test.go, pkg/util/yamlutil/yaml_test.go
/kind test
We can use the `T.TempDir` function from the `testing` package to create temporary directory. The directory created by `T.TempDir` is automatically removed when the test and all its subtests complete.
Reference: https://pkg.go.dev/testing#T.TempDir
N/A, this is a testing enhancement.
=> test: use `T.TempDir` to create temporary test directory

.github/workflows/e2e-tests.yaml, .github/workflows/lint.yaml, .github/workflows/unit-tests.yaml
=> Run GitHub action on v6 branch

cmd/deploy.go, cmd/dev.go, e2e/framework/util.go, e2e/kube/kube.go, e2e/tests/build/build.go, e2e/tests/build/testdata/buildkit/Dockerfile, e2e/tests/build/testdata/custom_build/Dockerfile, e2e/tests/command/command.go, e2e/tests/config/config.go, e2e/tests/dependencies/dependencies.go, e2e/tests/deploy/deploy.go, e2e/tests/devspacehelper/inject.go, e2e/tests/hooks/hooks.go, e2e/tests/init/init.go, e2e/tests/replacepods/replacepods.go, e2e/tests/sync/sync.go, e2e/tests/terminal/terminal.go, pkg/devspace/config/loader/loader.go, pkg/devspace/config/versions/v1beta11/upgrade.go, pkg/devspace/dependency/resolver.go, pkg/devspace/pipeline/engine/pipelinehandler/handler.go, pkg/devspace/pipeline/pipeline.go, pkg/devspace/services/podreplace/builder.go
=> WIP fix: update tests for v6

e2e/tests/pipelines/pipelines.go, e2e/tests/pipelines/testdata/getconfigvalue/devspace.yaml, pkg/devspace/pipeline/engine/pipelinehandler/commands/get_config_value.go, pkg/devspace/pipeline/engine/pipelinehandler/handler.go
=> feat: add get_config_value command

cmd/dev.go, cmd/overwrite_command.go, cmd/root.go, cmd/run.go, cmd/run_pipeline.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/v1beta11/upgrade.go
/kind feature
Allows to overwrite the `devspace dev`, `devspace deploy`, `devspace purge` and `devspace build` with custom commands
=> feat: allow command overwrite

cmd/run.go
=> fix: fix commands

pkg/devspace/services/ssh/config.go
=> fix: create ssh dir if missing

e2e/e2e_suite_test.go, e2e/tests/proxycommands/framework.go, e2e/tests/proxycommands/proxycommands.go, e2e/tests/proxycommands/testdata/proxycommands-simple/devspace.yaml, e2e/tests/proxycommands/testdata/proxycommands-simple/host-check.sh, e2e/tests/ssh/framework.go, e2e/tests/ssh/ssh.go, e2e/tests/ssh/testdata/ssh-simple/devspace.yaml
=> Add E2E Tests for SSH and Proxy Commands

Dockerfile
/kind bugfix
resolves #
git wasn't included in the image there fore dependencies: section with git proto didn't work.
Fixed an issue where DevSpace fails to interact with git dependencies.
=> add git to the image for dependencies

examples/buildkit-in-cluster/devspace.yaml, examples/buildkit/devspace.yaml, examples/custom-builder/devspace.yaml, examples/hot-reload-container-restart/devspace.yaml, examples/kaniko/devspace.yaml, examples/microservices/node/devspace.yaml, examples/microservices/php/devspace.yaml, examples/php-mysql-example/devspace.yaml, examples/redeploy-instead-of-hot-reload/devspace.yaml, pkg/devspace/config/loader/variable/command_variable.go, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/config/versions/v1beta11/upgrade.go, pkg/devspace/deploy/deployer/helm/deploy.go, pkg/devspace/deploy/deployer/kubectl/kubectl.go
`deployments.*.updateImageTags` is now default true
=> refactor: updateImageTags are now default true

cmd/add/add.go, cmd/add/plugin.go, cmd/completion.go, cmd/deploy.go, cmd/list/deployments.go, cmd/logs.go, cmd/print.go, cmd/purge.go, cmd/remove/remove.go, cmd/render.go, cmd/root.go, cmd/run.go, cmd/set/set.go, cmd/upgrade.go, cmd/use/context.go, cmd/use/namespace.go, cmd/use/use.go, cmd/version.go, dist/npm/index.js
/kind bugfix
resolves #
Uniform description
Fixed an issue where DevSpace ... commands will now have version sub command included. Also all the commands will have uniform description text.
=> Add version command and fix description

cmd/init.go, e2e/tests/dependencies/testdata/git/devspace.yaml, e2e/tests/dependencies/testdata/wait/dep1.yaml, e2e/tests/dependencies/testdata/wait/dep2.yaml, e2e/tests/dependencies/testdata/wait/devspace.yaml, e2e/tests/imports/testdata/local/devspace.yaml, pkg/devspace/config/versions/v1beta11/upgrade.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/create_deployments.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/run_dependency_pipelines.go, pkg/devspace/pipeline/engine/pipelinehandler/handler.go, pkg/devspace/pipeline/types/default.go, pkg/devspace/sync/sync.go
=> refactor: fix --from-file & rename run_dependency_pipelines

e2e/tests/imports/imports.go, e2e/tests/imports/testdata/local/devspace.yaml, e2e/tests/imports/testdata/local/import1.yaml, e2e/tests/imports/testdata/local/import2.yaml, e2e/tests/imports/testdata/local/import3.yaml, e2e/tests/imports/testdata/local/import4.yaml, e2e/tests/imports/testdata/local/import5.yaml, pkg/devspace/config/loader/imports.go, pkg/devspace/pipeline/engine/basichandler/commands/xargs.go
=> fix: fix xargs

pkg/devspace/dependency/util/util.go
=> refactor: do not clone git repos in parallel

e2e/tests/dependencies/dependencies.go, e2e/tests/dependencies/testdata/cyclic/dependency2/devspace.yaml, e2e/tests/dependencies/testdata/cyclic/devspace.yaml, e2e/tests/pipelines/pipelines.go, pkg/devspace/dependency/resolver.go, pkg/devspace/pipeline/pipeline.go
=> fix: cyclic dependency deployment

pkg/devspace/pipeline/engine/basichandler/commands/get_flag.go
=> refactor: use space as delimiter for get_flag

cmd/run.go, pkg/devspace/config/loader/variable/resolver.go
=> fix: variable resolver issue

e2e/framework/helper.go, e2e/tests/dependencies/dependencies.go, e2e/tests/dependencies/testdata/wait/dep1.yaml, e2e/tests/dependencies/testdata/wait/dep2.yaml, e2e/tests/pipelines/pipelines.go, e2e/tests/pipelines/testdata/flags/dep1.yaml, e2e/tests/pipelines/testdata/flags/devspace.yaml, pkg/devspace/context/values/values.go, pkg/devspace/deploy/deployer/kubectl/builder.go, pkg/devspace/pipeline/engine/basichandler/commands/get_flag.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/run_dependency_pipelines.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/run_pipelines.go, pkg/devspace/pipeline/pipeline.go, pkg/devspace/pipeline/types/pipeline.go, pkg/devspace/services/podreplace/builder.go
=> refactor: disable probes if image or command is replaced

cmd/print.go, pkg/devspace/config/loader/parser.go, pkg/devspace/dependency/manager.go, pkg/devspace/dependency/resolver.go
Relates to a possible improvement mentioned in https://github.com/loft-sh/devspace/issues/1829#issuecomment-995790591
Fixed an issue where DevSpace print would not resolve variables in under deployments.*.helm.values.
=> Resolve all config paths at the same time for devspace print

docs/src/css/content/markdown.scss
/kind bugfix
/kind feature
/kind test
resolves #
=> docs: replace is() selectors with where() selectors

docs/src/css/content/markdown.scss
/kind bugfix
/kind feature
/kind test
resolves #
=> docs: fix css for sass optimization

docs/src/js/details-clicks.js
/kind bugfix
/kind feature
/kind test
resolves #
=> docs: use regular interval for checking url hash

pkg/devspace/services/ssh/config.go
resolves #2102
DevSpace will now use a separate file for its ssh config
=> refactor: include separate ssh file

pkg/devspace/pipeline/engine/pipelinehandler/handler.go
/kind feature
Allows users to override pipeline functions
=> feat: allow command override

pkg/devspace/services/ssh/ssh.go
/kind bugfix
Fixed an issue where DevSpace would always use a different port for ssh
=> fix: stable ssh port

pkg/devspace/config/versions/v1beta11/upgrade.go, pkg/devspace/config/versions/validate.go, pkg/util/encoding/encoding.go
/kind bugfix
resolves #2132 
Fixed an issue where DevSpace ...underscores are allowed in command names now
=> Allow underscores in command names

docs/pages/configuration/dependencies/README.mdx
=> docs: dependencies update

cmd/list/ports.go, cmd/list/sync.go
/kind bugfix
resolves #2133
Fixed an issue where DevSpace ...listing of ports and sync works now
=> Add ports and sync listing

e2e/tests/imports/imports.go, e2e/tests/imports/testdata/local/devspace.yaml, e2e/tests/imports/testdata/local/profile_import.yaml, pkg/devspace/config/loader/imports.go, pkg/devspace/deploy/deployer/kubectl/kubectl.go
/kind feature
DevSpace now allows `profiles` and `hooks` in imports
=> feat: allow profiles & hooks in imports

docs/pages/configuration/dev/selectors/labels.mdx
=> docs: fix dev multiple containers

cmd/root.go, docs/pages/configuration/variables.mdx, pkg/devspace/services/ssh/config.go
=> refactor: add Match all to ssh config

docs/docusaurus.config.js
/kind bugfix
Resolves broken algolia search function
Fixed an issue where algolia search integration failed with updated docusaurus version.
=> adding rapid fix for algolia search

docs/pages/configuration/images/_partials/prevent_build.mdx
=> fixes typo

pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/deployer/helm/deploy.go
resolves #2150
Fixed an issue where DevSpace ...has now releaseName in helm config which will be used as release name.
=> replaced name in helm with releaseName field

docs/pages/configuration/variables.mdx
=> docs: update env file docs

cmd/list/vars.go, cmd/print.go, pkg/devspace/config/loader/variable/predefined_variable.go, pkg/devspace/config/loader/variable/resolver.go, pkg/util/downloader/commands/kubectl.go
=> feat: add DEVSPACE_EXECUTABLE environment variable

cmd/use/namespace.go, docs/pages/cli/devspace_use_namespace.md
to create the desired namespace if it doesn't exist yet.
resolves a request from Slack - https://loft-sh.slack.com/archives/C01NP55P8F6/p1657669283419999
Add a `--create` flag to the `devspace use namespace` command, which would automatically create the namespace if it doesn't exist.
=> feat: use namespace cmd accepts --create flag

cmd/run.go
=> fix: allow namespace & context for run

pkg/devspace/pipeline/engine/basichandler/commands/run_watch.go
=> feat: add --skip-init & --silent to run_watch

pkg/devspace/devpod/devpod.go
=> fix: issue with container replace

pkg/devspace/sync/upstream.go
/kind bugfix
Fixed an issue where DevSpace would always reupload empty files on initial sync.
=> fix: uploading empty files

cmd/analyze.go, cmd/attach.go, cmd/enter.go, cmd/flags/flags.go, cmd/list/deployments.go, cmd/list/namespaces.go, cmd/logs.go, cmd/open.go, cmd/reset/pods.go, cmd/restart.go, cmd/root.go, cmd/sync.go, cmd/ui.go, docs/pages/configuration/dev/connections/file-sync.mdx, docs/versioned_docs/version-4.x/configuration/development/file-synchronization.mdx, docs/versioned_docs/version-5.x/configuration/development/file-synchronization.mdx
/kind feature
resolves #2203 
Fixed an issue where DevSpace ...will have --kubeconfig flag on root level which will allow user to change kube configuration on the fly.
=> added support for kubeconfig flag in devspace

cmd/deploy.go, cmd/dev.go, cmd/purge.go, cmd/run_pipeline.go
=> refactor: allow arbitrary pipeline args

docs/pages/configuration/_partials/v2beta1/dev/containers/group_modifications.mdx, docs/pages/configuration/_partials/v2beta1/dev/containers/group_workflows_background.mdx, docs/pages/configuration/_partials/v2beta1/dev/containers/persistPaths.mdx, docs/pages/configuration/_partials/v2beta1/dev/containers/ssh.mdx, docs/pages/configuration/_partials/v2beta1/dev/containers/ssh/useInclude.mdx, docs/pages/configuration/_partials/v2beta1/dev/containers/ssh_reference.mdx, docs/pages/configuration/_partials/v2beta1/dev/containers_reference.mdx, docs/pages/configuration/_partials/v2beta1/dev/group_modifications.mdx, docs/pages/configuration/_partials/v2beta1/dev/group_workflows_background.mdx, docs/pages/configuration/_partials/v2beta1/dev/persistPaths.mdx, docs/pages/configuration/_partials/v2beta1/dev/ssh.mdx, docs/pages/configuration/_partials/v2beta1/dev/ssh/useInclude.mdx, docs/pages/configuration/_partials/v2beta1/dev/ssh_reference.mdx, docs/pages/configuration/_partials/v2beta1/dev_reference.mdx, docs/schemas/config-jsonschema.json, docs/schemas/config-openapi.json, pkg/devspace/config/versions/latest/schema.go
=> docs: update schema / partials

pkg/devspace/devpod/devpod.go
=> fix: allow insecure https for dev.open

docs/pages/configuration/profiles/activation.mdx
=> docs: fix activation page

devspace-schema.json, docs/hack/config/schemas/main.go, docs/schemas/config-openapi.json
=> docs: fix schema

docs/pages/configuration/_partials/v2beta1/dependencies/path.mdx, docs/pages/configuration/_partials/v2beta1/imports/path.mdx, docs/schemas/config-openapi.json
Modification the documentation to mention that path field can be a URL as well
=> Mention that path field can be a URL as well

docs/pages/getting-started/installation.mdx
=> docs: fix install

e2e/tests/config/config.go, e2e/tests/config/testdata/vars/devspace.yaml, pkg/devspace/config/loader/variable/resolver.go
/kind bugfix
resolves #2241
Fixed an issue where DevSpace wouldn't resolve environment variable vars correctly
=> fix: allow env as vars

pkg/devspace/server/server.go, ui/config/webpack.config.dev.js, ui/config/webpackDevServer.config.js, ui/package-lock.json, ui/package.json, ui/src/components/views/Commands/Commands/CommandsList/CommandsList.tsx, ui/src/contexts/withDevSpaceConfig/withDevSpaceConfig.tsx, ui/src/pages/commands/commands.tsx
/kind bugfix
resolves #2239
Fixed an issue where DevSpace commands were not usable in the DevSpace UI
=> fix: ui commands problem

pkg/devspace/config/versions/validate.go, pkg/util/yamlutil/yaml.go
resolves #2246
resolves #2247 
- Improved the output if a yaml parsing error occurs
- Print error if reserved function name is used in config
=> fix: improve unmarshal error

docs/pages/configuration/variables.mdx
=> docs: improve env var documentation

pkg/util/hash/hash.go
=> fix: deployment of component chart

docs/pages/ide-integration/visual-studio-code.mdx
=> docs: update visual studio code guide

.github/workflows/lint.yaml, cmd/root.go, pkg/devspace/config/loader/variable/command_variable.go, pkg/devspace/config/loader/variable/default_variable.go, pkg/devspace/config/loader/variable/expression/expression.go, pkg/devspace/helm/v3/client.go
/kind bugfix
**What does this pull request do?** 
Bump up the golangci-lint version.
=> fix: bump up golangci-lint version

docs/pages/configuration/profiles/patches.mdx
Specify that `imports` section  cannot be patched as well
=> Specify a new section that cannot be patched

docs/pages/configuration/dev/connections/open.mdx
`Open` documentation referred parameters from restartHelper
=> Change ConfigPartial ref for open feature

.vscode/launch.json
resolves #
Added launch config to debug devspace cli
=> Added config in launch.json to debug devspace cli

e2e/tests/render/testdata/helm/rendered.txt, pkg/devspace/config/loader/loader_test.go, pkg/devspace/config/loader/variable/expression/expression.go, pkg/devspace/deploy/deployer/helm/client.go
Bump the component chart to the latest version
Allow `$$()` to escape `$()` for config expressions
=> refactor: bump component chart

docs/pages/configuration/variables.mdx
Add documentation on missing predefined variables
=> Add missing documentation

pkg/devspace/kubectl/portforward/portforward.go
=> fix: make port forwarding non-blocking

docs/pages/configuration/_partials/v2beta1/deployments/updateImageTags.mdx
resolves #2285 
Update in doc to reflect proper default value of updateImageTags key.
=> Change default value of updateImageTags to true

docs/pages/configuration/deployments/helm/values.mdx
resolves #
Update about updateImageTags default value
=> Update about updateImageTags default value

pkg/devspace/pipeline/engine/basichandler/commands/xargs.go, pkg/devspace/pipeline/engine/basichandler/handler.go, pkg/devspace/pipeline/engine/pipelinehandler/handler.go
=> fix: use in built xargs only for pipeline commands

ui/src/components/views/Commands/Commands/CommandsList/CommandsList.tsx, ui/src/contexts/withDevSpaceConfig/withDevSpaceConfig.tsx, ui/src/pages/commands/commands.tsx
/kind bugfix
resolves #2294
Fixed an issue where DevSpace UI did not display commands from imported config file
=> fix: Use config key instead of rawConfig

cmd/root.go, cmd/run_pipeline.go, pkg/devspace/devpod/devpod.go, pkg/devspace/devpod/manager.go, pkg/devspace/kill/kill.go, pkg/devspace/kubectl/client.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/get_config_value.go, pkg/devspace/pipeline/engine/pipelinehandler/commands/start_dev.go, pkg/util/extract/unzip.go, pkg/util/idle/idle.go
=> refactor: improve sleep mode exit

cmd/init.go
/kind bugfix
resolves #2298
Fixed an issue where DevSpace encountered a fatal error during `devspace init`
=> fix: fatal error during devspace init

.github/workflows/docs.yaml, .github/workflows/e2e-tests.yaml, .github/workflows/lint.yaml, .github/workflows/npm.yaml, .github/workflows/release.yaml, .github/workflows/ui.yaml, .github/workflows/unit-tests.yaml, dist/npm/index.js, pkg/devspace/server/download.go, pkg/devspace/services/inject/inject.go, pkg/util/git/helper.go
/kind bugfix
/kind feature
/kind test
resolves #
=> fix: update asset download urls

cmd/cleanup/images.go
/kind bugfix
Devspace did not populate DEVSPACE_NAMESPACE variable when runnning `devspace cleanup images`
=> Specify a kubeClient when loading the devspace configuration

docs/pages/_partials/command_is_in.mdx, docs/pages/configuration/_partials/functions/group_checks.mdx, docs/pages/configuration/_partials/functions/group_checks_global.mdx, docs/pages/configuration/_partials/functions/is_in.mdx
resolves #2305
Add documentation about is_in function
=> docs: add is_in function documentation

docs/versioned_docs/version-5.x/fragments/workflow-open-links.mdx
=> Fixes a tiny typo

ui/package-lock.json, ui/src/components/basic/IconText/StatusIconText/StatusIconText.tsx, ui/src/images/dark-green-ellipse.svg
resolves #2331
Add dark-green color for pods which are in completed state
=> Add dark-green color for completed state pods

docs/pages/_partials/install-cli.mdx
resolves #2338
Update windows install instructions.
=> docs: remove incorrect note about environment variables with powershell

pkg/devspace/services/inject/inject.go
/kind bugfix
resolves #2334
Fixed an issue where DevSpace fails to detect the arch of a node of the pod.
=> fix: add check to detect the arch of node

docs/pages/configuration/dev/selectors/labels.mdx
/kind bugfix
resolves #
Fixes a typo in the documentation page Select Dev Container By Pod Labels
Fixed a typo in the documentation page Select Dev Container By Pod Labels
=> Fix typo in Select Dev Container By Pod Labels page

docs/pages/configuration/dev/selectors/labels.mdx
resolves #
Fix semantic error in the example code (line 14): It is not "reversePort", it is "reversePorts".
Fix semantic error in the example code
=> Documentation, fix semantic error in example

devspace-schema.json, docs/hack/config/schemas/main.go, docs/schemas/config-openapi.json
/kind bugfix
resolves #2339 
Add proper schema validation for vars
=> Add proper schema validation for vars

docs/pages/configuration/hooks/README.mdx, docs/sidebars.js
resolves #2362
Add hooks page in the docs for v6
=> Add Hooks page in docs

pkg/devspace/services/inject/inject.go
=> fix: arch detection in DevSpace

docs/pages/configuration/_partials/v2beta1/dependencies/group_execution.mdx, docs/pages/configuration/_partials/v2beta1/dependencies/profiles.mdx, docs/pages/configuration/dependencies/README.mdx
Documentation is missing a section about the profile parameter for dependency section
=> docs: add profiles partial for dependency

docs/pages/configuration/images/pull.mdx
Fixes the title of the "Pull" docs page.
N/A
=> docs: fix page title mistake

pkg/devspace/services/podreplace/builder.go
/kind bugfix
resolves #2403 
Improperly parsed volume names from claim templates when replacing StatefulSets
=> [fix] Improper parsing of volume name

cmd/root.go, pkg/devspace/plugin/plugin.go
resolves #
Pass all config vars to a DevSpace plugin command call, so they are available in the DevSpace plugin's environment
=> Pass on devspace vars to plugin env

pkg/devspace/generator/language_test.go, pkg/devspace/services/podreplace/builder.go, pkg/devspace/services/podreplace/replace.go
Fixes ENG-634
Improves DevSpace's deployment of `persistentPaths`
=> Scale down replica sets to allow transfer of persistPaths pvc between pods

devspace-schema.json, docs/pages/cli/devspace_cleanup_local-registry.md, docs/pages/configuration/_partials/v2beta1/localRegistry.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/enabled.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/image.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/name.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/namespace.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/persistence.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/persistence/enabled.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/persistence/size.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/persistence/storageClassName.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/persistence_reference.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/port.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry_reference.mdx, docs/pages/configuration/_partials/v2beta1/reference.mdx, docs/pages/configuration/images/push.mdx, docs/pages/configuration/localRegistry/README.mdx, docs/pages/getting-started/cleanup.mdx, docs/schemas/config-openapi.json, docs/sidebars.js, pkg/devspace/config/versions/latest/schema.go
Adds documentation for the local registry feature.
=> Local registry documentation

e2e/tests/localregistry/localregistry.go, e2e/tests/localregistry/testdata/local-registry-buildkit/devspace.yaml, e2e/tests/localregistry/testdata/local-registry-docker/devspace.yaml, e2e/tests/localregistry/testdata/local-registry-image-selectors/devspace.yaml, e2e/tests/localregistry/testdata/local-registry-kubectl/manifests/deployment.yaml, pkg/devspace/config/config.go, pkg/devspace/config/loader/variable/legacy/replace.go, pkg/devspace/config/loader/variable/legacy/replace_test.go
/kind bugfix
resolves #2441 
Fixes ENG-714
Fixed an issue where DevSpace is replacing container names and other values with image tags when it should only modify image tags
=> v6.2.0 Replaces containers names with image tags

docs/pages/configuration/variables.mdx
Change to _precedence_
Fix typo
Fixed a small spelling mistake in the docs
=> Fix a small typo

cmd/root.go, pkg/devspace/build/build.go, pkg/devspace/config/loader/imports.go, pkg/devspace/config/loader/loader.go, pkg/devspace/config/loader/parser.go, pkg/devspace/config/loader/variable/resolver.go, pkg/devspace/config/loader/variable/types.go, pkg/devspace/config/versions/versions.go
/kind bugfix
* Fixed an issue where DevSpace was wrongly resolving the image pull secrets on build
* Fixed an issue where DevSpace wasn't resolving imported variables correctly
=> fix: variable resolving & image pull secret creation

docs/pages/configuration/dev/README.mdx
/kind bugfix
/kind feature
/kind test
resolves #
=> resolves ENG-765 docs typo

pkg/devspace/build/build.go, pkg/devspace/build/create_builder.go
/kind bugfix
Fixed an issue where DevSpace would not create a needed pull secret
=> refactor: create pull secret

docs/pages/configuration/images/_partials/prevent_build.mdx
Fixed a grammatical error in DevSpace Documentation
=> docs: correct grammatical error

pkg/devspace/build/registry/util.go
=> refactor: improve local registry detection

pkg/devspace/helm/v3/client.go
/kind bugfix
resolves #2488
Fixes ENG-860
Fixed an issue where DevSpace would update helm dependencies in the wrong directory
=> Error 'Chart.yaml file is missing' reported for helm dependency update when custom chart name is used within dependency

pkg/devspace/build/registry/util.go, pkg/devspace/build/registry/util_test.go
/kind bugfix
resolves #2483
Fixes ENG-854
Fixed an issue where DevSpace would use the local registry when using an insecure registry
Also fixed a unit test panic and added additional test cases
=> Local Registry being used with insecure registry

docs/pages/configuration/dev/connections/terminal.mdx
resolves #2485 
Clarify container entrypoint replacement in `terminal`
=> docs: note on `terminal` container replacement

dist/npm/index.js, dist/npm/package.json
/kind bugfix
Updates registry URLs
=> fix: rename repository URLs

docs/pages/configuration/profiles/patches.mdx
resolves #2450
Fixes ENG-733
Updated patches examples to use up to date `path` examples for the `v2beta1` schema.
=> docs: update patch path examples to match v2beta1 schema

pkg/devspace/services/portforwarding/portforwarding.go
Signed-off-by: Alexis Sellier <alexis.sellier@ankorstore.com>
/kind bugfix
resolves #2535
Fixed an issue where reverse ports for specific container were not taken into account
=> fix: check for correct devcontainer reverse ports

devspace-schema.json, docs/pages/configuration/_partials/v2beta1/dependencies/disabled.mdx, docs/pages/configuration/_partials/v2beta1/dependencies/group_execution.mdx, docs/pages/configuration/_partials/v2beta1/dependencies_reference.mdx, docs/pages/configuration/_partials/v2beta1/deployments/kubectl/inlineManifest.mdx, docs/pages/configuration/_partials/v2beta1/deployments/kubectl_reference.mdx, docs/pages/configuration/_partials/v2beta1/images/kaniko/generateName.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry/buildKitImage.mdx, docs/pages/configuration/_partials/v2beta1/localRegistry_reference.mdx, docs/schemas/config-openapi.json, pkg/devspace/build/localregistry/options.go, pkg/devspace/config/versions/latest/schema.go
Signed-off-by: Fabian Kramm [fab.kramm@googlemail.com](mailto:fab.kramm@googlemail.com)
/kind feature
resolves #2538
Added a new option `localRegistry.buildKitImage` to specify the image for the buildkit builder
=> feat: add localRegistry.buildKitImage

pkg/devspace/config/versions/validate.go, pkg/devspace/config/versions/validate_test.go, pkg/util/progressreader/progressreader.go
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>
/kind bugfix
resolves #2535
As planned in the issue, after fix in #2536 we also need to ensure that a field in the dev pod is not also declared in the single container
=> fix: return error when a field is both in DevPod and DevContainer

e2e/tests/deploy/deploy.go, e2e/tests/deploy/testdata/helm-local-source/devspace-name.yaml, e2e/tests/deploy/testdata/helm-local-source/devspace-path.yaml, e2e/tests/deploy/testdata/helm-local-source/env.yaml, e2e/tests/deploy/testdata/helm-local-source/local-source/.helmignore, e2e/tests/deploy/testdata/helm-local-source/local-source/Chart.yaml, e2e/tests/deploy/testdata/helm-local-source/local-source/templates/NOTES.txt, e2e/tests/deploy/testdata/helm-local-source/local-source/templates/_helpers.tpl, e2e/tests/deploy/testdata/helm-local-source/local-source/templates/deployment.yaml, e2e/tests/deploy/testdata/helm-local-source/local-source/templates/hpa.yaml, e2e/tests/deploy/testdata/helm-local-source/local-source/templates/ingress.yaml, e2e/tests/deploy/testdata/helm-local-source/local-source/templates/service.yaml, e2e/tests/deploy/testdata/helm-local-source/local-source/templates/serviceaccount.yaml, e2e/tests/deploy/testdata/helm-local-source/local-source/templates/tests/test-connection.yaml, e2e/tests/deploy/testdata/helm-local-source/local-source/values.yaml, pkg/devspace/helm/v3/client.go
Signed-off-by: Russell Centanni <russell.centanni@gmail.com>
/kind bugfix
resolves #2523
fixes ENG-957
Use `--dependency-update` to avoid mismatched directories when updating helm dependencies.
=> fix: refactor helm dependency update to use --dependency-update

docs/pages/configuration/deployments/kubectl/inline_manifests.mdx
Signed-off-by: Luca Di Maio <luca.dimaio1@gmail.com>
resolves #2544 
closes ENG-1003
Improve inlineManifests docs, showing some example and interactions with expressions
=> docs: improve documentation for expressions with inlineManifests

devspace-schema.json, docs/pages/configuration/_partials/v2beta1/deployments/helm/disableDependencyUpdate.mdx, docs/pages/configuration/_partials/v2beta1/deployments/helm_reference.mdx, docs/schemas/config-openapi.json, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/deployer/helm/deploy_test.go, pkg/devspace/helm/v3/client.go
/kind feature
resolves #2533
Add a parameter to disable helm dependency update
=> feat: add a parameter to disable helm dependency update

dist/npm/index.js
Signed-off-by: Russell Centanni <russell.centanni@gmail.com>
/kind bugfix
resolves #2541
fixes ENG-998
Fixed an issue where DevSpace would fail to install using npm version 9 or greater.
=> fix: update node install scripts for npm 9

e2e/tests/dependencies/dependencies.go, e2e/tests/dependencies/testdata/cyclic/dependency2/devspace.yaml, pkg/devspace/dependency/resolver.go
/kind bugfix
resolves #2501
Fixes ENG-879
Silenced warning when working with the root of a cyclic dependency
=> fix: silence warning for cyclic dependency root

docs/pages/configuration/dev/connections/terminal.mdx
resolves #
Fix the typo introduced in #2502 
Fixed a typo in terminal docs
=> docs: fix a typo in terminal doc

cmd/list/ports.go
Add a json output to `devspace list ports` to align with other command
Add a json output to devspace list ports
=> feat: add a json output for list port command

go.mod, go.sum, vendor/github.com/emicklei/go-restful/v3/CHANGES.md, vendor/github.com/emicklei/go-restful/v3/README.md, vendor/github.com/emicklei/go-restful/v3/constants.go, vendor/github.com/emicklei/go-restful/v3/filter_adapter.go, vendor/github.com/emicklei/go-restful/v3/parameter.go, vendor/github.com/emicklei/go-restful/v3/request.go, vendor/github.com/emicklei/go-restful/v3/response.go, vendor/github.com/emicklei/go-restful/v3/route.go, vendor/github.com/emicklei/go-restful/v3/route_builder.go, vendor/github.com/emicklei/go-restful/v3/web_service.go, vendor/modules.txt
/kind bugfix
/kind security
resolves #
Updates go-restful and golang-jwt security issues https://github.com/emicklei/go-restful/issues/497 https://github.com/golang-jwt/jwt/issues/223#issuecomment-1302125635
=> Security fix for go-restful and golang-jwt

devspace-schema.json, docs/schemas/config-openapi.json, pkg/devspace/config/versions/latest/schema.go, pkg/devspace/deploy/deployer/helm/deploy_test.go
/kind bugfix
Resolves #2588 
Fixes ENG-1070
Make `disableDependencyUpdate` optional in `devspace-schema.json`
=> fix: Make disableDependencyUpdate optional in devspace-schema.json

docs/pages/configuration/images/build-engines/docker.mdx
Looks like there was a minor mistake in the documentation stating that fallback won't be triggered when `disableFallback` is false and should be true
/kind bugfix
/kind feature
/kind test
resolves #
=> Minor fix to `disableFallback` documentation

e2e/tests/restarthelper/restarthelper.go, e2e/tests/restarthelper/testdata/v5/devspace.yaml, e2e/tests/restarthelper/testdata/v6-inject-restart-helper/devspace.yaml, e2e/tests/restarthelper/testdata/v6-manual-start/devspace.yaml, e2e/tests/restarthelper/testdata/v6/devspace.yaml
/kind test
E2E tests started intermittently failing for #2609, this branch is to debug them.
=> Fix restart-helper e2e tests

e2e/tests/render/testdata/helm/rendered.txt, pkg/devspace/deploy/deployer/helm/client.go
=> Bump component chart

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
resolves ENG-1291
This PR adds a devcontainer json for developing devspace
=> chores: add devcontainer json for devspace

docs/pages/_partials/install-cli.mdx
Added installation section via scoop
resolves #2652
relates to #2629
Added new section to install DevSpace with Scoop
=> Scoop installation

e2e/tests/render/testdata/helm/rendered.txt, pkg/devspace/deploy/deployer/helm/client.go
/kind bugfix
resolves #2703
Fixes ENG-1974
Update component chart version
=> fix: update component chart version

pkg/devspace/kubectl/util.go
=> feat: add orbstack to local K8s

pkg/devspace/pipeline/pipeline.go
=> fix: nil pointer in ensure namespace

cmd/cleanup/local_registry.go
/kind bugfix
resolves #
fix errror messages when clean up local registry
fix errror messages when clean up local registry
=> fix: fix typo

docs/pages/getting-started/introduction.mdx
(docs) adds the DevSpace Video Tutorial Series to the introduction page to help users get started
(docs) adds the DevSpace Video Tutorial Series to the introduction page to help users get started
=> added video tutorial series playlist to introduction to DevSpace

.github/workflows/e2e-tests.yaml, e2e/tests/ssh/ssh.go
/kind test
Test is currently failing due to #2415, so this is a temporary measure to allow unrelated PRs to be approved
Fixed an issue where DevSpace E2E tests take several attempts to pass.
Temporary until $2415 can be properly fixed.
=> test: add flake attempts and fail-fast for e2e tests

pkg/devspace/services/podreplace/builder.go, pkg/devspace/services/sync/sync.go
/kind bugfix
resolves #2782 
resolves #2783
- Fixed an issue where DevSpace does not mount persistent paths when using multiple containers.
- Fixed an issue where DevSpace fails to notify containers of initial sync completion when using multiple containers.
=> Fix issues when using multiple containers in one pod

e2e/tests/ssh/ssh.go, e2e/tests/ssh/testdata/ssh-simple/devspace.yaml, e2e/tests/ssh/testdata/ssh-variable/devspace.yaml
/kind bugfix
resolves #2415
resolves ENG-2328
Fixed an issue where DevSpace concurrency causes issues with helm deployments
Mostly debugging this, since the issue appears more often in CI/CD workflows.
=> SSH test improvements

pkg/devspace/services/podreplace/builder.go
/kind bugfix
resolves #2776
Fixed an issue where the `containerName` is too long
=> fix: use string hash for volumeName

pkg/devspace/configure/deployment.go
/kind bugfix
resolves #
N/A
Fixed an issue where DevSpace check for only kustomization.yaml extension 
added support for kustomization.yml extension as well.
=> added support for kustomization.yml

.github/workflows/release.yaml
=> fix: update upload-artifact action

pkg/devspace/sync/util_test.go
resolves #
Directly swap variable values
=> refactor: Directly swap variable values

README.md
Fixes the URL of the build status badge.
Fixed the build status badge in the readme file. ref: badges/shields#8671
Nothing
=> Fix the build status badge

docs/pages/configuration/_partials/functions/start_dev/disable-open.mdx, pkg/devspace/devpod/manager.go
resolves #2791
Corrected the description for --disable-open flag.
=> Correct the description for --disable-open flag.

pkg/devspace/context/values/values.go, pkg/devspace/kubectl/testing/client.go, pkg/util/factory/testing/factory.go
resolves #
make function comment match function name
=> chore: make function comment match function name

pkg/devspace/config/loader/variable/undefined_variable.go
/kind bugfix
resolves #2971
Fixed an issue where DevSpace would default a string var to "`<nil>`"
=> fix: prevent using "<nil>" as default value
